### ISSUE TITLE
Should we use the mock or the instance?

### ISSUE THREAD

**Issue by katlim-br** [m-radzikowski/aws-sdk-client-mock#103]
**Checklist**

- [ x] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**
This is not so much a bug, but more of a question.

The code we use typically is like this (pardon this is just a quick dirty pseudocode to exemplify the idea):
```
globals.js
module.exports = {
  s3Client: new S3Client(process.env.region)
}

index.js
const { s3Client } = require("./globals")

// dependecy container
const cnt = { 
  s3Client 
}

code.js
async function code(cnt) {
  cnt.s3Client.send(GetObjectCommand)
  or
  await new Upload() { client: cnt.s3Client, ....).done();
}
```

So when we do the tests:
```
const { code  } = require(".")
const mockS3 = mockClient(s3Client) // <<< instance, we dont mock the class

const cnt = {
  s3Client: mockS3  <<<<<< here is the doubt
}

it("my test", async() => {
  mockS3.on(GetObjectCommand, resolves: { ... })
  await code(cnt)
})
```

Before version 1.0.0 of your lib and before AWS version 112 (around 87 and below), we used to set `cnt.s3Client = mockS3`. But in the new versions we had to do `cnt.s3Client = s3Client` (which matches the examples in the documentation).

We had to do this basically because our tests that used the Upload class failed (if we stick to .send(Command), the error does not show up).

Two questions:
1. Was there a change that made this happen?
2. Was our original implementation (cnt.s3Client = mockS3) good? Or it was always wrong?

Thanks

**Environment**

- Node version: 14
- Testing lib and version: jest
- Typescript version: js
- AWS SDK v3 Client mock version: 1.0.0
- AWS JS SDK libs and versions: 3.112

**Comment by m-radzikowski** [comment]
Ad. 2. No, you should use the "real" AWS SDK Client instance. The library replaces the `send()` method with a mocked one, which also exists in the returned mock. But theoretically, the SDK Client instance could expose other methods than `send()` and they would not exist in the mock instance. So you should not replace the Client instance with the mock.

Ad. 1. I'm not sure what exactly caused this issue but in v1.0.0 I've added package.json `exports` providing separate paths to the "main" mock and libStorage mock, which seems to be the case.

**Comment by katlim-br** [comment]
thanks for the answer
