### ISSUE TITLE
How to force an exception

### ISSUE THREAD

**Issue by rmclaughlin-nelnet** [m-radzikowski/aws-sdk-client-mock#106]
I am using this library in my tests and so far it is great. However I am a unsure about how to use this to force an exception.

for example I am doing this

```
const {
  DynamoDBDocumentClient,
  UpdateCommand,
} = require('@aws-sdk/lib-dynamodb');
const {
  ConditionalCheckFailedException,
} = require('@aws-sdk/client-dynamodb');

const ddbMock = mockClient(DynamoDBDocumentClient);
ddbMock.on(UpdateCommand).rejects(ConditionalCheckFailedException);
```

However that does not throw the proper exception. Any ideas on what I need to do differently?

The code I am testing looks like this
```
if (error instanceof ConditionalCheckFailedException) {
      ...
}
```

For reference:
https://aws.amazon.com/blogs/developer/service-error-handling-modular-aws-sdk-js/
https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.DynamoDb.Exception.DynamoDbException.html#shape-conditionalcheckfailedexception

**Comment by automartin5000** [comment]
@rmclaughlin-nelnet 

This is not working for me, I'm getting a `An argument for 'opts' was not provided.` when using `ddbMock.on(UpdateCommand).rejects(new ConditionalCheckFailedException());`
Any ideas?

**Comment by automartin5000** [comment]
Actually, I was able to work around this with `ddbMock.on(UpdateCommand).rejects(new ConditionalCheckFailedException('' as any));`

**Comment by say8425** [comment]
I mocked Secrets Manager and had same issue. any is not looks good but anyway it works. Thanks.
