### ISSUE TITLE
After upgrading to 1.0.0. jest tests are failing in our ES6 node app

### ISSUE THREAD

**Issue by kesavab** [m-radzikowski/aws-sdk-client-mock#107]
**Checklist**

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**

I am developing a nodejs ES6 serverless project. I am using jest for unit testing and this package for mocking aws calls. When I upgrade this package from 0.6.2 to  1.0.0, I am getting this error 

est suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /projectpath/node_modules/aws-sdk-client-mock/dist/es/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from './mockClient';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1796:14)

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From src/create.test.js.

          at async Promise.all (index 1)

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From src/create.test.js.

          at async Promise.all (index 3)

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From src/create.test.js.

          at async Promise.all (index 0)

**Reproduction**

https://github.com/kesavab/recreate-aws-sdk-client-mock-jest-issue

**Environment**

- Node version: v14.17.6
- Testing lib and version: Jest
- Typescript version: na
- AWS SDK v3 Client mock version: 1.0.0
- AWS JS SDK libs and versions:
  - 
         "@aws-sdk/client-dynamodb": "^3.113.0",
        "@aws-sdk/client-sqs": "^3.109.0",
        "@aws-sdk/lib-dynamodb": "^3.113.0",

**Comment by m-radzikowski** [comment]
Please try the `v2.0.0-beta.1` and let me know if the problem occurs with it.

**Comment by kesavab** [comment]
Thanks it worked. :)
