### ISSUE TITLE
Trying to understand the documentation

### ISSUE THREAD

**Issue by rwc0920** [m-radzikowski/aws-sdk-client-mock#114]
Currently try to mock the aws s3 service. 

![Screen Shot 2022-08-29 at 2 54 53 PM](https://user-images.githubusercontent.com/66286416/187306039-45dec529-1fbe-4afa-88d2-bf632d42efe6.png)

This screenshot is from the documentation and I'm trying to figure out where "new Upload" is being imported from because it doesn't exist in the package.

Can someone please help me out?

**Comment by m-radzikowski** [comment]
It's from the `@aws-sdk/lib-storage` as noted right above the code. But you are right, the import was missing in the code example, I've updated it.
