### ISSUE TITLE
Returning meta data

### ISSUE THREAD

**Issue by rwc0920** [m-radzikowski/aws-sdk-client-mock#115]
<img width="1193" alt="Screen Shot 2022-08-31 at 10 52 34 AM" src="https://user-images.githubusercontent.com/66286416/187746547-e2be34fa-991a-4f25-ad8c-defbe993e63e.png">

After using the Upload class to upload a document, isn't there suppose to be some meta data associated in the response?  Is there a reason you can't use PutObjectCommand to upload a document? If so, how can we use it with the mock service?

**Comment by m-radzikowski** [comment]
The `Upload` class is a helper from the `@aws-sdk/lib-storage` for uploading files of any size. The `PutObjectCommand` [is not suitable for uploading larger files](https://docs.aws.amazon.com/AmazonS3/latest/userguide/upload-objects.html), instead you should upload them in chunks using multipart upload. `lib-storage` does it for you.

As you can read further down in the readme, just below the part you screenshotted above:

> For uploading a small file (under the defined multipart upload single part size), lib-storage sends a PutObjectCommand. To make it fail:
s3Mock.on(PutObjectCommand).rejects();
For bigger files, it makes a series of calls including CreateMultipartUploadCommand, UploadPartCommand, and CompleteMultipartUploadCommand. Making any of them fail will fail the upload:
s3Mock.on(UploadPartCommand).rejects();

The mocking lib does not mock the `Upload` itself, so its behavior (and returned metadata) will match what would happen depending on the result of the Commands used internally (`PutObjectCommand`, `CreateMultipartUploadCommand`, `UploadPartCommand`, and `CompleteMultipartUploadCommand`) that you can mock.
