### ISSUE TITLE
Issue with documentation on mocking s3 client

### ISSUE THREAD

**Issue by rwc0920** [m-radzikowski/aws-sdk-client-mock#117]
<img width="833" alt="Screen Shot 2022-09-13 at 12 34 05 PM" src="https://user-images.githubusercontent.com/66286416/189993342-59c78098-9bba-435c-b6f1-222145f4dbf7.png">

The above example is a screenshot of the documentation provided for uploading a document. How come 's3Mock' isn't being passed in as the client in s3Upload?

**Comment by m-radzikowski** [comment]
Did you actually try it to check if it works before opening an issue suggesting it's the docs mistake?

As stated in the [readme](https://github.com/m-radzikowski/obsidian.git), you can mock all (existing and further) instances of the Client by mocking not a specific client instance, but a class.

In this case, we do:

```ts
import {S3Client} from '@aws-sdk/client-s3';
const s3Mock = mockClient(S3Client);
```

so then when we create a new Client **instance** (`new S3Client({})`) it is mocked.
