### ISSUE TITLE
await upload.done(): Mock Error

### ISSUE THREAD

**Issue by sharmmoh1983** [m-radzikowski/aws-sdk-client-mock#118]
**Checklist**

I saw the readme file and tried to mock S3 upload

- [x] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**

I am trying to mock  { Upload } from "@aws-sdk/lib-storage"; using aws-sdk-client-mock but getting error Error: Region is missing

**Reproduction**
```

import {S3Client, CreateMultipartUploadCommand, UploadPartCommand,PutObjectCommand} from "@aws-sdk/client-s3";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
const s3Mock = mockClient(S3Client);
// @ts-ignore
s3Mock.on(CreateMultipartUploadCommand).resolves({UploadId: "1"});
// @ts-ignore

s3Mock.on(UploadPartCommand).resolves({ETag: "1"});
// @ts-ignore
s3Mock.on(PutObjectCommand).resolves({ETag: "1"});

 this.s3Client =   new S3Client(config.isOffline === "true"? {
            forcePathStyle: true,
            credentials: {
                accessKeyId: "S3RVER", 
                secretAccessKey: "S3RVER",
            },
            endpoint: "http://localhost:4569",
        } : { region: config.region });
 try {
            const upload = new Upload({
                client: this.s3Client,
                params: params
            });
 const results = await upload.done();

```
**Environment**

- Node version: v16 
- Testing lib and version:     "mocha": "^10.0.0",

- Typescript version:  "typescript": "^4.7.4",
- AWS SDK v3 Client mock version:    "aws-sdk-client-mock": "^1.0.0",
- AWS JS SDK libs and versions: "@aws-sdk/client-s3": "^3.171.0",

**Comment by m-radzikowski** [comment]
This runs fine:

```ts
import {CreateMultipartUploadCommand, PutObjectCommand, S3Client, UploadPartCommand} from '@aws-sdk/client-s3';
import {Upload} from '@aws-sdk/lib-storage';
import {mockClient} from 'aws-sdk-client-mock';

const s3Mock = mockClient(S3Client);
s3Mock.on(CreateMultipartUploadCommand).resolves({UploadId: '1'});

s3Mock.on(UploadPartCommand).resolves({ETag: '1'});
s3Mock.on(PutObjectCommand).resolves({ETag: '1'});

const s3Client = new S3Client({
    forcePathStyle: true,
    credentials: {
        accessKeyId: 'S3RVER',
        secretAccessKey: 'S3RVER',
    },
    endpoint: 'http://localhost:4569',
});

it('runs', async () => {
    const upload = new Upload({
        client: s3Client,
        params: {
            Bucket: '',
            Key: '',
            Body: 'x'.repeat(6 * 1024 * 1024), // 6 MB
        },
    });
    const results = await upload.done();
});
```

with `@aws-sdk/client-s3` and `@aws-sdk/lib-storage` in version **exactly** 3.171.0.

Please:

- try to run this test case I provided above in isolation and check if it works or not
- check the exact version of the `@aws-sdk` libs (the `^3.171.0` means you can have any version between 3.171.0 and 4.0.0)

**Comment by bitblit** [comment]
Perhaps this is the wrong place to address this question, but as I am running into a similar issue to this one, I'll drop it here (Happy to open a separate one otherwise).

Unless I am missing something obvious - which I probably am - both this code and the official documentation for using upload create a mock object (named s3Mock) and then... proceeds to not use it, instead creating a new s3Client (named s3Client here, anonymous in the officials docs) and passing that to the upload object instead of the mock.  If one instead passes the mock object to the Upload object like so:

mockS3 = mockClient(S3Client);
mockS3.on(PutObjectCommand).resolves({});
mockS3.on(CreateMultipartUploadCommand).resolves({ UploadId: '1' });
mockS3.on(UploadPartCommand).resolves({ ETag: '1' });

const upload: Upload = new Upload({
      client: mockS3,
      params: params, // Put a PutObjectCommandInput in here...
      tags: [],
      queueSize: 4,
      partSize: 1024 * 1024 * 5,
      leavePartsOnError: false,
    });

One will get an error :
Cannot read properties of undefined (reading 'requestHandler')

because the mock doesn't define a client config.

**Comment by bitblit** [comment]
Having dug deeper into the system, I think I now understand where my previous comment was off - leaving this comment in case anyone else ends up in the same place.

When this library mocks clients it appears to do so to the prototype, not to the instance (I haven't read the code to verify that - just going by observed behavior.  Feel free to correct me).  So, as in my example above, when you write

mockS3 = mockClient(S3Client);

then the prototype for S3Client itself is modified, such that any future S3Client is _also_ a mock, including ones created via:

x = new S3Client();

This also means that you can't really mix mocks and reals of any particular client in a piece of code (probably not a good idea anyway, but definitely wouldn't give you the results you want).

**Comment by m-radzikowski** [comment]
> When this library mocks clients it appears to do so to the prototype, not to the instance

You can mock either the prototype (`mockClient(S3Client)`) or the instance (`mockClient(new S3Client({}))`). If you mock the prototype, all clients are mocked. If you mock an instance, only this specific instance is mocked.

`mockClient()` function returns a mock, not the mocked Client itself. In `Upload` you must provide the Client, not the mock. Just like in the example in the README: https://github.com/m-radzikowski/aws-sdk-client-mock#lib-storage-upload

Hope this clarifies things. I'm going to close this, feel free to open a new issue if needed.
