### ISSUE TITLE
TypeScript error when providing object to "Resolves" -- "not assignable to parameter of type CommandResponse<MetadataBearer>

### ISSUE THREAD

**Issue by Antonio-Riccelli** [m-radzikowski/aws-sdk-client-mock#119]
**Checklist**

I read the readme and tried to mock `AWS.CognitoIdentityServiceProvider.signUp()`. 

- [x] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**

I have different functions in my TypeScript/Node/Express backend that call methods from CognitoIdentityServiceProvider. I'm trying to mock them in my tests, starting from `signUp`, but when I'm trying to provide a value to `resolves`, I get the following error:

`
Argument of type '{ CodeDeliveryDetails: {}; }' is not assignable to parameter of type 'CommandResponse<MetadataBearer>'.
  Object literal may only specify known properties, and 'CodeDeliveryDetails' does not exist in type 'CommandResponse<MetadataBearer>'.ts(2345)
`

The object I'm trying to pass is the standard object returned by the `signUp` response, as per API: [API link](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SignUp.html)

I'm not very experienced with this and trying this particular library for the first time, so please be kind 😅 Many thanks.

**Reproduction**

```
import { mockClient } from "aws-sdk-client-mock";
import AWS from "aws-sdk";
import { createUser } from "../controllers/AuthController";

const cognito: any = new AWS.CognitoIdentityServiceProvider();
const cognitoMock = mockClient(cognito);

beforeEach(() => {
  cognitoMock.reset();
});

describe("The authentication module", () => {
  it("successfully creates a user", () => {
    cognitoMock.on(cognito.signUp).resolves({
        CodeDeliveryDetails: {

        }
    })
  });
});
```

**Environment**

- Node version: v18.7.0
- Testing lib and version:  Jest
- Typescript version: ^4.7.4
- AWS SDK v3 Client mock version: ^2.0.0
- AWS JS SDK libs and versions: 
  - 
  - "aws-sdk": "^2.1166.0"
  - "@aws-sdk/client-cognito-identity-provider": "^3.121.0",
  - "amazon-cognito-identity-js": "^5.2.9",

(not necessarily using all the libs in the code, just listing what I have)

**Comment by m-radzikowski** [comment]
Hey,
you are using the AWS JS SDK v2 (`aws-sdk`). This mocking library is for the AWS JS SDK v3 (`@aws-sdk/*`): https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html

Your options are:

- switch to the SDK v3 and use this mocking lib
- mock SDK v2 calls (either manually or with [aws-sdk-mock](https://github.com/dwyl/aws-sdk-mock) lib)
