### ISSUE TITLE
Types of the stubbed client to be interchangeable with the client types

### ISSUE THREAD

**Issue by edwardrose946** [m-radzikowski/aws-sdk-client-mock#120]
Firstly thanks for the great repo.

I'm new to a project and we're transitioning node.js services to use TS. We've had to do an ugly work around to pass the mocked client around. Since the mocked ECS client is a AwsClientStub<Client<TInput, TOutput, any>> we can't easily pass it to functions expecting an ECSClient for example:

```
import { ECSClient } from "@aws-sdk/client-ecs";
import { mockClient } from "aws-sdk-client-mock";

export class MyService {
  client: ECSClient;
  constructor(client: ECSClient) {
    this.client = client;
  }
}

// test.ts
const ecsMock = mockClient(ECSClient);
ecsMock.on(RunTaskCommand).resolves({
  tasks: [{ taskArn: "123" }],
});
// brute force into an ECSClient type
const myService = new MyService(
    // ugly
    ecsMock as unknown as ECSClient
);
```
It would be great for the type of the mocked client to be interchangeable with the type of the client that was passed in the constructor. Is this outside what the library has been designed to do or is there a better work around?

**Comment by ebuildy** [comment]
The returned mocked client  is not a real client, this should work:

```
const ecsMock = mockClient(ECSClient);
ecsMock.on(RunTaskCommand).resolves({
  tasks: [{ taskArn: "123" }],
});
// brute force into an ECSClient type
const myService = new MyService(
    new ECSClient()
);
```

**Comment by m-radzikowski** [comment]
You should still use the real AWS SDK Client instance. The result of the `mockClient()` is not the new Client that you should use to make AWS SDK calls, but an object to instrument the mocking behavior for the (real) Client.

So what @ebuildy suggests is correct - you still use the regular `ECSClient`, it can even be created later in code than a `mockClient()` call.

Another example:

```ts
import {mockClient} from 'aws-sdk-client-mock';
import {PublishCommand, SNSClient} from '@aws-sdk/client-sns';

const snsMock = mockClient(SNSClient); // this is the mock instrumentation object

it('works', async () => {
    snsMock // instrument how the mock should behave
        .on(PublishCommand)
        .resolves({
            MessageId: '12345678-1111-2222-3333-111122223333',
        });

    // create and use SDK Client to send an SDK Command
    const sns = new SNSClient({}); // this is the SDK Client
    await sns.send(new PublishCommand({TopicArn: '', Message: ''}));

    // use mock object to verify sent command
    expect(snsMock.commandCalls(PublishCommand).length).toBe(1);
});
```

**Comment by edwardrose946** [comment]
Thanks for both responses. Instrument how the mock behaves, create and pass around a new client (will have the mock behaviour). Fantastic, thanks lads.
