### ISSUE TITLE
Type errors mocking Secrets Manager SDK

### ISSUE THREAD

**Issue by joshuacoveauth0** [m-radzikowski/aws-sdk-client-mock#121]
**Checklist**

- [x] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**
When attempting to mock AWS Secrets Manager with the code below, getting Type errors on the `SecretsManagerClient` and `GetSecretValueCommand`.
These errors persist when installing `@aws-sdk/types` and when pinning all aws-sdk packages to the same version.
```
import {
    SecretsManagerClient,
    GetSecretValueCommand
  } from '@aws-sdk/client-secrets-manager';
  import { generateDotEnvContents } from '../utils';
  import { getSecretsFromSecretManager } from '../aws';

  describe('with aws mocked', () => {
     const smMock = mockClient(SecretsManagerClient);
     smMock.on(GetSecretValueCommand).resolves({ 
       SecretString: JSON.stringify({ my_secret_key: 'my_secret_value' })
     });

    beforeEach(() => { 
      smMock.reset();
    });

    it('does stuff', async () => {
      const result = await generateDotEnvContents(dotEnvPath)

      expect(result).toEqual({
        DOMAIN: 'my-domain.com',
        MY_SECRET: 'my-secret',
        MY_SECRET_2: 'my-secret-2'
      })

      expect(smMock).toHaveReceivedCommandTimes(GetSecretValueCommand, 1);
    })
  })
```

**Reproduction**

**Environment**

- Node version: v16.16.0
- Testing lib and version: jest 28.1.3
- Typescript version: 4.7.4
- AWS SDK v3 Client mock version: 1.0.0, 2.0.0
- AWS JS SDK libs and versions:
  - "@aws-sdk/client-secrets-manager": "^3.171.0", or 3.142.0

**Comment by CelestialMusa** [comment]
Hi @joshuacoveauth0

Try using non-ES6 import for your AWS libraries like so: 
`
const {
    SecretsManagerClient,
    GetSecretValueCommand
} = require('@aws-sdk/client-secrets-manager');`

`const { mockClient } = require("aws-sdk-client-mock");`

and then proceed to create a new instance of the mock client as you have:
`const smMock = mockClient(SecretsManagerClient);`

I noticed that there's an inconsistency between @aws-sdk/types library used by aws-sdk-client-mock and the @aws-sdk/client-secrets-manager libraries.

There's a MiddlewareStack interface that declares a method `identify(): string[]` within the typings used by @aws-sdk/client-secrets-manager which is not present in the version of typings used by aws-sdk-client-mock.

I would like to contribute to fixing this on this library, but have no idea how - best bet would be to lookup versions of aws-sdk-client-mock and @aws-sdk/client-secrets-manager that use the same version of the @aws-sdk/types library.

Using non-ES6 import style is not the best solution but it helped me resolve this issue.

**Comment by m-radzikowski** [comment]
With TypeScript v4.7.4 and `@aws-sdk/client-secrets-manager` v3.142.0 this works perfectly fine for me:

```ts
import {GetSecretValueCommand, SecretsManagerClient} from '@aws-sdk/client-secrets-manager';
import {mockClient} from 'aws-sdk-client-mock';
import 'aws-sdk-client-mock-jest';

describe('with aws mocked', () => {
    const smMock = mockClient(SecretsManagerClient);

    beforeEach(() => {
        smMock.reset();
    });

    it('does stuff', async () => {
        smMock.on(GetSecretValueCommand).resolves({
            SecretString: JSON.stringify({my_secret_key: 'my_secret_value'}),
        });

        const sm = new SecretsManagerClient({});
        const result = await sm.send(new GetSecretValueCommand({
            SecretId: '',
        }));

        expect(result).toEqual({
            SecretString: '{"my_secret_key":"my_secret_value"}',
        });

        expect(smMock).toHaveReceivedCommandTimes(GetSecretValueCommand, 1);
    });
});
```

Please try to run it in isolation from other parts of your code. If the problem persists, please include what errors you are getting.

**Comment by joshuacoveauth0** [comment]
@CelestialMusa 
Yes, this works fine with `@aws-sdk/client-secrets-manager v3.142.0`, though not with the version I was using at first, `@aws-sdk/client-secrets-manager v3.171.0`.
We can use the older version, so the test is working as intended now.
Thanks for your help!
