### ISSUE TITLE
calling reset before tests breaks S3 mock

### ISSUE THREAD

**Issue by jfpaccini** [m-radzikowski/aws-sdk-client-mock#123]
**Checklist**

- [x] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**

When mocking S3Client with a resolve(), if 'reset()' is called on mocked client before any test has ran, the mocked S3Client returns undefined.

I was trying to mock the GetObjectCommand action on the S3Client, with a Stream returned as the Body component in the answer. Some tests suites were working fine, while another one was failing. After some hours, I realized that the failing test suite had a beforeEach clause containing `s3mock.reset()`.

I could reduce it to the following example. Uncommenting the `s3Mock.reset()` breaks the test: the `answer` is undefined.

This is in contradiction with the Lambda example in the documentation saying __To be sure that unit tests are independent from each other, reset mock behavior between the tests.__ with the reset in the beforeEach section. 

Putting the reset in the afterEach section works fine.

thanks
jfp

- [x] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for t
 

**Reproduction**

```Javascript
require("aws-sdk-client-mock-jest");
const { mockClient } = require("aws-sdk-client-mock");
const { S3Client, GetObjectCommand } = require("@aws-sdk/client-s3");

const s3Mock = mockClient(S3Client);

s3Mock.on(GetObjectCommand).resolves({
  Body: "should actually be a Stream",
});

const s3Client = new S3Client();

// uncommenting the following line breaks the test
// s3Mock.reset();

it("should retrieve file from S3", async () => {
  const commandParameters = {
    Bucket: "whatever",
    Key: "file",
  };

  const answer = await s3Client.send(new GetObjectCommand(commandParameters));
  expect(answer.Body).toEqual("should actually be a Stream");
  expect(s3Mock).toHaveReceivedCommandWith(GetObjectCommand, {
    Bucket: "whatever",
    Key: "file",
  });
});
```

**Environment**

- Node version: Node 16
- Testing lib and version: Jest v26
- Typescript version: n/a
- AWS SDK v3 Client mock version: ^2.0.0
- AWS JS SDK libs and versions: ^3.118.0

**Comment by m-radzikowski** [comment]
Well, you set up the mock, then reset it, then run the test.

To have tests (and mocks) independent from each other, you should reset it before each test and only then set up the mock. For example:

```ts
let snsMock: AwsClientStub<SNSClient>;

beforeEach(() => {
    snsMock = mockClient(SNSClient);

   // here put mocking behavior that you want to have in every test
    snsMock
        .on(PublishCommand)
        .resolves({
            MessageId: '12345678-1111-2222-3333-111122223333',
        });
});

it('runs', async () => {
    // here put mocking behavior for this particular test only
    snsMock
        .on(PublishCommand)
        .resolves({
            MessageId: '12345678-1111-2222-3333-111122223333',
        });

    // test...
});
```

**Comment by jfpaccini** [comment]
Thanks. looks like I was confusing mock.reset() with mock.clear()..
