### ISSUE TITLE
objectContaining not working after upgrading to 2.0.0

### ISSUE THREAD

**Issue by delsinz** [m-radzikowski/aws-sdk-client-mock#129]
**Checklist**

- [x] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**

`expect.objectContaining` does not work anymore after upgrading to 2.0.0 and importing `aws-sdk-client-mock-jest` in test file.

**Reproduction**
This piece of test code used to work:
```typescript
for (let i = 1; i <= 10; i++) {
  expect(snsClientMock).toHaveReceivedNthCommandWith(
    i,
    PublishCommand,
    expect.objectContaining({
      TopicArn: 'test-topic',
    }),
  );
}
```

After upgrading to 2.0.0, it fails to ignore the the rest of the fields in the call even though `TopicArn` still exists.

Test failure message:
```
Expected SNSClient to receive 1. "PublishCommand" with ObjectContaining {"TopicArn": "test-topic"}
    SNSClient received "PublishCommand" with input:
    - Expected  - 1
    + Received  + 9

    - ObjectContaining {
    + Object {
    +   "Message": "some test message...",
    +   "MessageAttributes": Object {
    +     "Type": Object {
    +       "DataType": "String",
    +       "StringValue": "Communication",
    +     },
    +   },
    +   "Subject": "MessageMetadataEvent/v1",
        "TopicArn": "test-topic",
      }
```

**Environment**

- Node version: 16.15.1
- Testing lib and version: Jest 29.1.2
- Typescript version: 
- AWS SDK v3 Client mock version: 2.0.0
- AWS JS SDK libs and versions: 3.137.0

**Comment by wrumsby** [comment]
@delsinz based on my use of v2 it seems like the matcher performs an object containing match, e.g. if you change your code to:

```
for (let i = 1; i <= 10; i++) {
  expect(snsClientMock).toHaveReceivedNthCommandWith(
    i,
    PublishCommand,
    {
      TopicArn: 'test-topic',
    },
  );
}
```

it should work! It certainly does for me.

**Comment by delsinz** [comment]
> @delsinz based on my use of v2 it seems like the matcher performs an object containing match, e.g. if you change your code to:
> 
> ```
> for (let i = 1; i <= 10; i++) {
>   expect(snsClientMock).toHaveReceivedNthCommandWith(
>     i,
>     PublishCommand,
>     {
>       TopicArn: 'test-topic',
>     },
>   );
> }
> ```
> 
> it should work! It certainly does for me.

Thanks @wrumsby! It does work.

@m-radzikowski could you possibly document this behavior of the matcher in README please?

**Comment by delsinz** [comment]
@m-radzikowski Is there any way to "tighten" the matching rules and disable this default `objectContaining` matching behavior in my tests?

**Comment by m-radzikowski** [comment]
@delsinz this is exactly as in the examples in the README:

```ts
expect(snsMock).toHaveReceivedCommandWith(PublishCommand, {Message: 'My message'});
```

The `expect.objectContaining` call is made [internally](https://github.com/m-radzikowski/aws-sdk-client-mock/blob/main/packages/aws-sdk-client-mock-jest/src/jestMatchers.ts#L275). The `aws-sdk-client-mock-jest` is a utility to validate sent commands, and doing the `objectContaining` makes sense for most cases. If you have a more complex scenario and you absolutely need a different behavior, you will need to handle it yourself:

```ts
expect(snsMock.commandCalls(PublishCommand)[0].args[0].input).toEqual(...)
```
