### ISSUE TITLE
Argument of type .... is not assignable to parameter of type 'CommandResponse<MetadataBearer>'

### ISSUE THREAD

**Issue by sebsonjura** [m-radzikowski/aws-sdk-client-mock#136]
**Checklist**

- [x] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**
I am trying to mock a s3 client doing a ListObjectsV2Command and had to find out no mocks for s3 client work for me. 

**Reproduction**

simple thing I try to do: 

```
    s3ClientMock
      .on(ListObjectsV2Command)
      .resolves({ IsTruncated: true })
````

Result Error: Argument of type '{ IsTruncated: boolean; }' is not assignable to parameter of type 'CommandResponse<MetadataBearer>'.
  Object literal may only specify known properties, and 'IsTruncated' does not exist in type 'CommandResponse<MetadataBearer>'.

**Environment**

````
  "devDependencies": {
    "@types/jest": "29.2.3",
    "@types/node": "18.11.9",
    "aws-sdk-client-mock": "2.0.1",
    "jest": "29.3.1",
    "ts-jest": "29.0.3",
    "typescript": "4.9.3"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@aws-sdk/client-s3": "3.218.0",
    "@types/async": "3.2.16",
    "@types/aws-lambda": "8.10.109",
    "@types/aws-sdk": "2.7.0",
    "async": "3.2.4",
    "promise-mysql": "5.2.0"
  }
```


- Node version:  18.x
- Testing lib and version:Jest 
- Typescript version: 4.9.3
- AWS SDK v3 Client mock version:  2.0.1
- AWS JS SDK libs and versions:  "@aws-sdk/client-s3": "3.218.0

p.s. There is no version 3.218.0 of @types/aws-sdk

**Comment by sebs** [comment]
Update: 

the problem appears when I am using import to get me the mockClient into a file.

This works - 
```
const { mockClient } = require("aws-sdk-client-mock");
```

**Comment by m-radzikowski** [comment]
Hey,
this code works just fine for me:

```ts
import {ListObjectsV2Command, S3Client} from '@aws-sdk/client-s3';
import {mockClient} from 'aws-sdk-client-mock';

const s3Mock = mockClient(S3Client);
s3Mock
    .on(ListObjectsV2Command)
    .resolves({IsTruncated: true});
```

with `@aws-sdk/client-s3` both v3.218.0 and v3.224.0 (latest today).

The issue may be with conflicting TS types, but your dependencies do not suggest any other package that could cause conflicts.

The `@types/aws-sdk` are types for SDK v2, not v3. You don't need it.

Types for SDK v3 are in `@aws-sdk/types`, but you generally don't need to install it yourself unless to solve types conflicts.

Please:

- update the `@aws-sdk/client-s3` to the latest version and check if the problem persists?
- run `yarn why @aws-sdk/types` or `npm ls @aws-sdk/types` and paste the result here for further debug.

**Comment by sebs** [comment]
ill use it again on 27th. 

Ill report any issues. Thanks for the reply! very kind

**Comment by epeters3** [comment]
I was getting similar type errors to this, and adding an `@aws-sdk/types` resolution to my `package.json` fixed the issue for me, so all packages are using the same version of `@aws-sdk/types` now in my project. Loved [the docs](https://github.com/m-radzikowski/aws-sdk-client-mock#mixed-aws-sdktypes-versions) there, thanks!
