### ISSUE TITLE
Asserting constructor arguments

### ISSUE THREAD

**Issue by DarylLyonsLF** [m-radzikowski/aws-sdk-client-mock#144]
Hi, is it possible to access the arguments that were passed to the AWS client at instantiation and if not, could this be considered for a future enhancement?

Thanks in advance and apologies if I have missed something obvious here.

---
#### SUT
```js
export default class MyClass {
  constructor(region) {
    this.client = new SNSClient({ region });
  }
}
```
#### Test
```js
const snsClientMock = mockClient(SNSClient);
const sut = new MyClass('eu-west-1');
// Assert SNSClient was instantiated with { region: 'eu-west-1'}
```

**Comment by air2** [comment]
In my project I initiate a couple of clients (for specific account/regions) and call commands, now I want to see which client called the command. This could be done for example if the mock command would mock  a specific client (with specific constructor arguments) so I could differentiate between those clients. Or, when the constructor arguments are accesible when handling a command (for example in the .on event (maybe a specialized .on event) anyway this would help me greatly in testing my code.

**Comment by GerardSoleCa** [comment]
Hi,

Same here, I don't see a way to assert arguments in the constructor. Did someone find a way?

Cheers!

**Comment by m-radzikowski** [comment]
Hey all,
the library mocks (or, to be specific, stubs) only the `send()` method of SDK Clients. This is on purpose, to not interfere with any other methods or logic that SDK has, like middlewares.

However, the SDK Clients expose the resolved config object. If you have access to the Client, you can access it to check the region for example:

```ts
it('gets the Client region', async () => {
    const sns = new SNSClient({
        region: 'eu-west-2',
    });

    expect(await sns.config.region()).toBe('eu-west-2');
});
```

Mocking the specific Client instance (with `mockClient(sns)`) or Client prototype (with `mockClient(SNSClient)`) does not matter here.

---

To assert anything about the Client, you need to have access to it.

You can access the Client from the mock instance for a specific `send()` call:

```ts
import {mockClient} from 'aws-sdk-client-mock';
import {PublishCommand, SNSClient} from '@aws-sdk/client-sns';

it('gets the Client region', async () => {
    const snsMock = mockClient(SNSClient);

    const snsEU = new SNSClient({
        region: 'eu-west-2',
    });
    await snsEU.send(new PublishCommand({TopicArn: 'mock', Message: 'mock'}));

    const snsUS = new SNSClient({
        region: 'us-east-1',
    });
    await snsUS.send(new PublishCommand({TopicArn: 'mock', Message: 'mock'}));

    expect(await snsMock.call(0).thisValue.config.region()).toBe('eu-west-2');
    expect(await snsMock.call(1).thisValue.config.region()).toBe('us-east-1');

    snsMock.restore();
});
```

You can access mock calls with `call()`, `calls()`, and `commandCalls()` methods. Then, with `thisValue` you can access the Client used to send the given Command.

---

Hope this helps and solves your use cases. I will keep the issue open for a time, let me know if you have any further questions.

**Comment by DarylLyonsLF** [comment]
Thanks for the help @m-radzikowski. This addresses my original query and I've not got anything to follow up with so I'll mark issue as closed.

Thanks again!

**Comment by kpeters-cbsi** [comment]
> Hey all, the library mocks (or, to be specific, stubs) only the `send()` method of SDK Clients. This is on purpose, to not interfere with any other methods or logic that SDK has, like middlewares.
> 
> However, the SDK Clients expose the resolved config object. If you have access to the Client, you can access it to check the region for example:
> 
> ```ts
> it('gets the Client region', async () => {
>     const sns = new SNSClient({
>         region: 'eu-west-2',
>     });
> 
>     expect(await sns.config.region()).toBe('eu-west-2');
> });
> ```
> 
> Mocking the specific Client instance (with `mockClient(sns)`) or Client prototype (with `mockClient(SNSClient)`) does not matter here.
> 
> To assert anything about the Client, you need to have access to it.
> 
> You can access the Client from the mock instance for a specific `send()` call:
> 
> ```ts
> import {mockClient} from 'aws-sdk-client-mock';
> import {PublishCommand, SNSClient} from '@aws-sdk/client-sns';
> 
> it('gets the Client region', async () => {
>     const snsMock = mockClient(SNSClient);
> 
>     const snsEU = new SNSClient({
>         region: 'eu-west-2',
>     });
>     await snsEU.send(new PublishCommand({TopicArn: 'mock', Message: 'mock'}));
> 
>     const snsUS = new SNSClient({
>         region: 'us-east-1',
>     });
>     await snsUS.send(new PublishCommand({TopicArn: 'mock', Message: 'mock'}));
> 
>     expect(await snsMock.call(0).thisValue.config.region()).toBe('eu-west-2');
>     expect(await snsMock.call(1).thisValue.config.region()).toBe('us-east-1');
> 
>     snsMock.restore();
> });
> ```
> 
> You can access mock calls with `call()`, `calls()`, and `commandCalls()` methods. Then, with `thisValue` you can access the Client used to send the given Command.
> 
> Hope this helps and solves your use cases. I will keep the issue open for a time, let me know if you have any further questions.

I have a use case where this doesn't work. Suppose I have a function:
```
import { SNSClient, SNSClientConfig } from '@aws-sdk/client-sns';
export default function factory(args: SNSClientConfig) { 
  const snsclient =  new SNSClient(args);
  return new MyClass(snsclient);
}

class MyClass {
  constructor(private snsclient: SNSClient) {}
}
```

There's no way for me to access `MyClass.snsclient` to check that it was configured properly *without* calling `send`. While I could update the test to call `send`, it adds extra complication to the test when it would be simpler to have a way to inspect the parameters of the actual constructor.

**Comment by m-radzikowski** [comment]
> I have a use case where this doesn't work. Suppose I have a function:
> 
> ```
> import { SNSClient, SNSClientConfig } from '@aws-sdk/client-sns';
> export default function factory(args: SNSClientConfig) { 
>   const snsclient =  new SNSClient(args);
>   return new MyClass(snsclient);
> }
> 
> class MyClass {
>   constructor(private snsclient: SNSClient) {}
> }
> ```
> 
> There's no way for me to access `MyClass.snsclient` to check that it was configured properly _without_ calling `send`. While I could update the test to call `send`, it adds extra complication to the test when it would be simpler to have a way to inspect the parameters of the actual constructor.

That's equivalent to:

```ts
class A {
	constructor(private param: string) {
	}
}

class B {
	private a: A;
	constructor() {
		this.a = new A('some value');
	}
}

new B(); // how to test B.a.param value ?
```

So it's a generic code testability thing, not something this lib can help with.
