### ISSUE TITLE
Mocking not working (region is missing error)

### ISSUE THREAD

**Issue by joaopedromatias** [m-radzikowski/aws-sdk-client-mock#149]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

I'm trying to mock the following function: 

```ts
import { DynamoDBClient, GetItemCommand } from '@aws-sdk/client-dynamodb'

const dynamoClient = new DynamoDBClient({})

export const handler = async () => {
const getItemCommand = new GetItemCommand({
      TableName: 'whatever',
      Key: {
        createdBy: {
          S: 'user'
        }
      }
    })
    const data = await dynamoClient.send(getItemCommand)
   return data.Item
  }
```

By running the following code: 

```ts
import { DynamoDBClient, GetItemCommand } from '@aws-sdk/client-dynamodb'
import { mockClient } from 'aws-sdk-client-mock'
import { handler } from '../../src/report/index'

const dynamoDBMock = mockClient(DynamoDBClient)

beforeEach(() => {
  dynamoDBMock.restore()
})

describe('get', () => {
  it('should return the dynamoDB mocked items', async () => {
    dynamoDBMock.on(GetItemCommand).resolves({
      Item: {
        foo: { S: 'bar' }
      }
    })

    const result = await handler()
    expect(result.foo.S).toBe('bar')
  })
})
```

But I'm receiving the `Region is missing` error, like if I'm not authenticated on AWS on my computer

<img width="727" alt="Captura de Tela 2023-03-08 às 14 32 43" src="https://user-images.githubusercontent.com/90068133/223787115-e3ec568c-f12a-4ebe-ab85-809247100cfa.png">

How can I solve this issue? I don't know if it's a Dynamo mocking particularity, because the SNS on the docs worked here.

### Reproduction

yarn dev

### Environment

- Node version: 18.12.1
- Testing lib and version: Jest 29.4.3
- Typescript version: 4.9.5
- AWS SDK v3 Client mock version: 3.282.0
- AWS JS SDK libs and versions:
    -

**Comment by joaopedromatias** [comment]
Man, I don't know why it was not working before, but now it does 🤯 

Thanks for the awesome lib 🚀

**Comment by mjdavidson** [comment]
@joaopedromatias what was the issue here I'm getting the same error

**Comment by joaopedromatias** [comment]
@mjdavidson you probably need to have the AWS region env var on project or set it on machine via the AWS CLI
