### ISSUE TITLE
Allow partial payload match

### ISSUE THREAD

**Issue by angarg12** [m-radzikowski/aws-sdk-client-mock#15]
As I understand, currently payload matches are strict. However, sometimes we care only about a single field (e.g. some id or name) out of otherwise large objects. Writing these full objects creates bloated test codes.

It would be great to have the option to define partial matchers for payloads.

**Comment by m-radzikowski** [comment]
Good idea. I think it may be even a default behavior, with a "strict" mode enabled by additional param. It was actually quite easy to do, I have a PR ready: #16 I will test it some more and release a new version.

**Comment by m-radzikowski** [comment]
Released in v0.4.0
