### ISSUE TITLE
NPM Readme

### ISSUE THREAD

**Issue by shellscape** [m-radzikowski/aws-sdk-client-mock#150]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

_Super_ minor issue, but the way the package is being published doesn't appear to ship a README with it and NPM is having trouble fetching a README automagically from the repo.

### Reproduction

 https://www.npmjs.com/package/aws-sdk-client-mock

Possible solutions:

- use a publishing tool that will include the root readme in your package before the `pack` stage,
- use a prepack and postpack step that will copy the root readme into the directory for deploy, and remove it when done packing (pnpm does something similar with LICENSE files)

### Environment

- Node version: n/a
- Testing lib and version: n/a
- Typescript version: n/a
- AWS SDK v3 Client mock version: latest
- AWS JS SDK libs and versions: latest

**Comment by m-radzikowski** [comment]
Hey, thanks for the info. Yes, README should be added to the published package. In a few minutes, I will release a new version that includes it.

Could you tell me how you access the README from the installed package? Asking from curiosity. I always go to the project README online on github 😉

**Comment by shellscape** [comment]
Most folks won't access the readme from the installed package, but they _will_ view the readme on npmjs.com, and in order for that site to render it, it has to be accessible in the package.

**Comment by m-radzikowski** [comment]
Oh, right. I did not realize that went gone when I changed the repo structure 🤦 

Thanks again!
