### ISSUE TITLE
S3 GetObjectCommand does not respect bytes param

### ISSUE THREAD

**Issue by abhinav-enboarder** [m-radzikowski/aws-sdk-client-mock#151]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

When calling GetObjectCommand with bytes parameter, the stream should skip and limit the bytes by respecting the param.

### Reproduction

```js
new GetObjectCommand({
  "Bucket": process.env.BUCKET,
  "Key": path,
  "Range": `bytes=${startMarker}-${endMarker}`
});
```

### Environment

- Node version: 18
- Testing lib and version: jest 29.4.2
- Typescript version: NA
- AWS SDK v3 Client mock version: 2.1.1
- AWS JS SDK libs and versions:
    - @aws-sdk/client-s3: 3.290.0

**Comment by m-radzikowski** [comment]
Your description and example are short and not clear, not even including the mocking library... What I suppose you want to achieve is something like this:

```ts
const s3Mock = mockClient(S3Client);

it('mocks get object', async () => {
    const stream = new Readable();
    stream.push('hello world');
    stream.push(null); // end of stream

    const sdkStream = sdkStreamMixin(stream);

    s3Mock.on(GetObjectCommand).resolves({Body: sdkStream});

    const s3 = new S3Client({});

    const getObjectResult = await s3.send(new GetObjectCommand({
        Bucket: 'foo',
        Key: 'bar',
        Range: 'bytes=0-5'
    }));

    const str = await getObjectResult.Body?.transformToString();

    expect(str).toBe('hello'); // fails, returned content is "hello world"
});
```

The mocking library does not process the Command parameters in any way. What you specify to be resolved is what you get in the response.

What you can do, is to implement your mocking logic with `callsFake()`:

```ts
s3Mock
    .on(GetObjectCommand)
    .callsFake(input => {
        // prepare and return the body stream trimmed down to the specified `input.Range`
    });
```

Please reopen if you have further questions.

**Comment by abhinav-enboarder** [comment]
Thanks this helps solve the issue!
