### ISSUE TITLE
export a function to explicitly bind to Jest expect

### ISSUE THREAD

**Issue by zebehringer** [m-radzikowski/aws-sdk-client-mock#156]
I see the snippet for using the matchers outside of Jest
```
const {expect} = require("expect");
(globalThis as any).expect = expect;
require("aws-sdk-client-mock-jest");
```
but that does not seem compatible with our code as a an ES6 module, and I think the asynchronousness of module imports causes the matchers not to get extended on `expect`.

Maybe if there were a function exported from the Jest module that could be called in `beforeEach` where we could pass in `expect` and have the matchers extended on that, then I could get around this problem.

Please excuse my naivety.

**Comment by m-radzikowski** [comment]
Hey, sorry for the late reply.

Jest matchers are added to the `expect` in a standard way as per [docs](https://jestjs.io/docs/expect#expectextendmatchers):

```ts
expect.extend(...)
```

So I would hope you can make it work as it is.

I'm not really into the idea of exporting anything else for this single use case, as it then becomes something I can't modify without a breaking change.

That being said, the matchers are just little helpers that you can recreate by inspecting mock calls: https://github.com/m-radzikowski/aws-sdk-client-mock#inspect

I'm closing this, but please let me know if you have any further questions.
