### ISSUE TITLE
Not each Client is supported , for example KMSClient

### ISSUE THREAD

**Issue by RobertDittmann** [m-radzikowski/aws-sdk-client-mock#160]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Used versions:

- "@aws-sdk/client-kms": "^3.329.0",
- "aws-sdk-client-mock": "^2.1.1",

<img width="1604" alt="Screenshot 2023-05-12 at 16 54 28" src="https://github.com/m-radzikowski/aws-sdk-client-mock/assets/11576433/b788734e-253a-4ae0-8de6-15b80d127a7c">

### Reproduction

`import { KMSClient } from "@aws-sdk/client-kms";`
`import {mockClient} from 'aws-sdk-client-mock';`
`const mock = mockClient(KMSClient)`

### Environment

- "@aws-sdk/client-kms": "^3.329.0",
- "aws-sdk-client-mock": "^2.1.1",

**Comment by m-radzikowski** [comment]
Hey Robert :D
 
Please double-check that: https://github.com/m-radzikowski/aws-sdk-client-mock#mixed-aws-sdktypes-versions

The types error you are getting is typical for having multiple `@aws-sdk/types` versions installed and conflicting.

You can run `yarn why @aws-sdk/types` (or similar for npm/pnpm) to check it.

**Comment by RobertDittmann** [comment]
COOOL 💯  :)
