### ISSUE TITLE
v2.1.1 does not work with DynamoDBDocumentClient

### ISSUE THREAD

**Issue by Opus4210** [m-radzikowski/aws-sdk-client-mock#165]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Using the sample you provided ([DynamoDB DocumentClient](https://github.com/m-radzikowski/aws-sdk-client-mock#dynamodb-documentclient)), `mockClient` will not accept DynamoDBDocumentClient, neither as a type nor an instance of that type.

This code:
```
import {DynamoDBClient} from '@aws-sdk/client-dynamodb';
import {DynamoDBDocumentClient, QueryCommand} from '@aws-sdk/lib-dynamodb';

const ddbMock = mockClient(DynamoDBDocumentClient);
```
results in the following Intellisense error:
```
Argument of type 'typeof DynamoDBDocumentClient' is not assignable to parameter of type 'InstanceOrClassType<Client<ServiceInputTypes, ServiceOutputTypes, any>>'.
  Type 'typeof DynamoDBDocumentClient' is not assignable to type 'ClassType<Client<ServiceInputTypes, ServiceOutputTypes, any>>'.
    The types of 'prototype.middlewareStack' are incompatible between these types.
      Property 'identify' is missing in type 'import("/home/kedie/dev/git/vlncc-backend/node_modules/@aws-sdk/node-config-provider/node_modules/@aws-sdk/types/types/middleware").MiddlewareStack<import("/home/kedie/dev/git/vlncc-backend/node_modules/@aws-sdk/lib-dynamodb/dist-types/DynamoDBDocumentClient").ServiceInputTypes, import("/home/kedie/dev/git/vlncc-bac...' but required in type 'import("/home/kedie/dev/git/vlncc-backend/node_modules/@aws-sdk/types/dist-types/middleware").MiddlewareStack<import("/home/kedie/dev/git/vlncc-backend/node_modules/@aws-sdk/lib-dynamodb/dist-types/DynamoDBDocumentClient").ServiceInputTypes, import("/home/kedie/dev/git/vlncc-backend/node_modules/@aws-sdk/lib-dynamod...'.ts(2345)
```

### Reproduction

```
import { DynamoDBDocumentClient } from '@aws-sdk/lib-dynamodb';

const ddbMock = mockClient(DynamoDBDocumentClient);
```
or
```
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient } from '@aws-sdk/lib-dynamodb';

const ddb = new DynamoDBClient({});
const client = DynamoDBDocumentClient.from(ddb);
const ddbMock = mockClient(client);
```
or
```
import { DynamoDB } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient } from '@aws-sdk/lib-dynamodb';

const ddb = new DynamoDB({});
const client = DynamoDBDocumentClient.from(ddb);
const ddbMock = mockClient(client);
```

### Environment

- Node version: 18.6.0
- `typescript` version: 4.9.5
- `jest` version: 29.5.0
- `aws-sdk-client-mock` version: 2.1.1
- `aws-sdk-client-mock-jest` version: 2.1.1
- `@aws-sdk/client-dynamodb` version`: 3.347.0
- `@aws-sdk/lib-dynamodb` version`: 3.347.0
- `@aws-sdk/types` version: 3.347.0

**Comment by m-radzikowski** [comment]
I can take a look later, but from the error message I can say it's 99% incompatibility between `@aws-sdk/types` used by `aws-sdk-client-mock` and SDK libs. Apparently can happen even if you explicitly define it in `package.json`.

You can try:

- forcing `@aws-sdk/types` version with [overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides)
- removing `node_modules` and `package-lock.json` and reinstalling dependencies - drastic step, but you can check if that will help

Otherwise, please create an empty project, put all the libs you listed in `package.json`, and install dependencies. If you can reproduce it that way - please put repo on github and link it here.

**Comment by Opus4210** [comment]
I sent you to my repo. I have run your unit tests and they pass, so I'm really baffled. I even tried adding every single package that your project has.

ftr the full error that I get when I run the test looks like this:
```
error TS2345: Argument of type 'typeof DynamoDBDocumentClient' is not assignable to parameter of type 'InstanceOrClassType<Client<ServiceInputTypes, MetadataBearer, any>>'.
      Type 'typeof DynamoDBDocumentClient' is not assignable to type 'ClassType<Client<ServiceInputTypes, MetadataBearer, any>>'.
        The types of 'prototype.middlewareStack.concat' are incompatible between these types.
          Type '<InputType extends ServiceInputTypes, OutputType extends ServiceOutputTypes>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<...>' is not assignable to type '<InputType extends ServiceInputTypes, OutputType extends MetadataBearer>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<InputType, OutputType>'.
            Types of parameters 'from' and 'from' are incompatible.
              Property 'identify' is missing in type 'MiddlewareStack<InputType, OutputType>' but required in type 'MiddlewareStack<InputType, ServiceOutputTypes>'.

    14 const ddbMock = mockClient(DynamoDBDocumentClient);
                                  ~~~~~~~~~~~~~~~~~~~~~~

      node_modules/@aws-sdk/smithy-client/node_modules/@aws-sdk/types/dist-types/middleware.d.ts:411:5
        411     identify(): string[];
                ~~~~~~~~~~~~~~~~~~~~~
        'identify' is declared here.
```
so it looks like it's declared but not defined?

**Comment by Opus4210** [comment]
In my project, where I was still seeing problems, I updated the @aws-sdk packages to version 3.347.0 and now the code works. I'm doubly confused now because the project in which I originally experienced the problem is already using that version. I'll re-check my configuration.

**Comment by Opus4210** [comment]
Somehow, in the project that was still failing, there was something in `package-lock.json` that was preventing all the packages from updating correctly. My tests are now working as expected. Sorry for the trouble.

**Comment by m-radzikowski** [comment]
Running `npm ls @aws-sdk/types` on the repo you created returns:

```
├─┬ @aws-sdk/lib-dynamodb@3.49.0
│ ├─┬ @aws-sdk/smithy-client@3.347.0
│ │ └── @aws-sdk/types@3.347.0
│ └── @aws-sdk/types@3.49.0 deduped
└── @aws-sdk/types@3.49.0
```

That's probably because SDK packages have peer dependencies on `^3.0.0` - from `@aws-sdk/lib-dynamodb` package.json:

```json
  "peerDependencies": {
    "@aws-sdk/client-dynamodb": "^3.0.0",
    "@aws-sdk/smithy-client": "^3.0.0",
    "@aws-sdk/types": "^3.0.0"
  },
```

And npm installs peer dependencies by default. And probably once the dependencies are installed, it's not always so smart to dedupe them, even when you add `@aws-sdk/types` with type explicitly, especially if the already installed version is higher.

Anyway, I will think about making it more visible in the docs, to save others time. I'm glad you made it work. Thanks for posting the repo with reproduction though!

**Comment by sawilde** [comment]
I had this issue with AWS SDK 3.363 and after upgrading aws-sdk-client-mock v3 

I resolved this by nuking my yarn.lock file and rebuilding it - a lot of dependant packages were updated but the issue did resolve itself
