### ISSUE TITLE
Upgrade to AWS SKD 3.369.0 breaks mock functionality

### ISSUE THREAD

**Issue by mariuszch** [m-radzikowski/aws-sdk-client-mock#174]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Hi, updating aws sdk packages to version 3.369.0 breaks mock functionality, please see the screenshot attached. 
It fails the same way for all 4 I use in my project: Dynamo, IotDataPlane, S3, STS

Looks like some type mismatch, because it works fine when I use ts-expect-error flag

![image](https://github.com/m-radzikowski/aws-sdk-client-mock/assets/13779221/4e87c782-251e-431c-9eb0-02c8e00b1ef0)

### Reproduction

const stsClientMock = mockClient(STSClient)

### Environment

    "@aws-sdk/client-dynamodb": "^3.369.0",
    "@aws-sdk/client-iot": "^3.369.0",
    "@aws-sdk/client-iot-data-plane": "^3.369.0",
    "@aws-sdk/client-s3": "^3.369.0",
    "@aws-sdk/client-sts": "^3.369.0",
    "@aws-sdk/lib-dynamodb": "^3.369.0",
    "@aws-sdk/util-stream-node": "^3.369.0",
    "aws-sdk-client-mock": "^3.0.0",

**Comment by hoonoh** [comment]
I got around this by adding dependency resolutions on `@smithy/smithy-client` to `1.0.3`.

I didn't dive deep into this, but `@smithy/smithy-client` released `1.0.4` about a week ago and all aws client packages had dependency on this package marked as `^1.0.3`. I guess there might be breaking changes between those versions.

**Comment by m-radzikowski** [comment]
@mariuszch lib v3.0.0 works correctly with AWS SDK 3.369.0 and above - see example: https://codesandbox.io/s/typescript-playground-export-forked-th3ng6

Please make sure all your `@aws-sdk/*` and `@smithy/*` libs [are in the same version](https://github.com/m-radzikowski/aws-sdk-client-mock#mixed-aws-sdktypes-versions)

**Comment by j03w** [comment]
in my case my dependencies have both `@smithy/types` 2.1 and 2.2 so as a quick hack I added `@smithy/types` 2.2 as dev dependencies and that solved the problem for me
