### ISSUE TITLE
It looks like Smithy client type changed (Again)

### ISSUE THREAD

**Issue by air2** [m-radzikowski/aws-sdk-client-mock#177]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

When upgrading s3 and some other libs to 3.174.0 (from 3.170.0) the mocking stuff stopped compiling again. I noticed the clients are now extending Client from `@smithy/client` instead of `@smithy/types` so the client cannot be passed to the `mockClient` function anymore.

### Reproduction

```
import { mockClient } from 'aws-sdk-client-mock'
describe('test', () => {
   it('test mock', () => {
     const mock = mockClient(S3Client)
   })
})
```

### Environment

- Node version: v18.16.0
- Testing lib and version: 
    - jasmine v5.0.2
    -  jasmine-core v5.0.1
- Typescript version: 5.1.5
- AWS SDK v3 Client mock version: 3.0.0
- AWS JS SDK libs and versions: 
      -         "@aws-sdk/client-acm": "^3.370.0",
      -         "@aws-sdk/client-backup": "^3.370.0",
      -         "@aws-sdk/client-cloudformation": "^3.373.0",
      -         "@aws-sdk/client-cloudwatch-logs": "^3.370.0",
      -         "@aws-sdk/client-cognito-identity-provider": "^3.370.0",
      -         "@aws-sdk/client-dynamodb": "^3.370.0",
      -         "@aws-sdk/client-efs": "^3.370.0",
      -         "@aws-sdk/client-elastic-beanstalk": "^3.370.0",
      -         "@aws-sdk/client-elastic-load-balancing-v2": "^3.370.0",
      -         "@aws-sdk/client-kms": "^3.370.0",
      -         "@aws-sdk/client-route-53": "^3.370.0",
      -         "@aws-sdk/client-s3": "^3.374.0",
      -         "@aws-sdk/client-secrets-manager": "^3.370.0",
      -         "@aws-sdk/client-sns": "^3.370.0",
      -         "@aws-sdk/client-sqs": "^3.370.0",
      -         "@aws-sdk/client-ssm": "^3.370.0",
      -         "@aws-sdk/credential-providers": "^3.370.0",
      -         "@aws-sdk/lib-storage": "^3.374.0",

**Comment by m-radzikowski** [comment]
Hey, I'm not getting any errors with library v3.0.0 with AWS SDK v3.370.0 or v3.374.0. See sandbox: https://codesandbox.io/s/typescript-playground-export-forked-th3ng6

Please make sure all your `@aws-sdk/*` packages point to the same version - right now with the mix of `^3.370.0` and `^3.374.0` it's likely they are not.
