### ISSUE TITLE
Use Jest matchers without requiring on every test file

### ISSUE THREAD

**Issue by glhrmv** [m-radzikowski/aws-sdk-client-mock#178]
Hey all, quick question: is it possible to use the matchers (like `.toHaveReceivedCommandWith()`) without having to `require`/`import` the matchers package at the top every test file? I have many test files and I would appreciate not having to deal with this quirk by importing it *globally* once, somehow.

Ideally I would add something to the Jest configuration file, but I'm not super familiar with Jest config.

**Comment by m-radzikowski** [comment]
You can create `jest.setup.ts` file with the import:

```ts
import 'aws-sdk-client-mock-jest';
```

and add it to `setupFilesAfterEnv` in jest config:

```json
  "jest": {
    "preset": "ts-jest",
    "setupFilesAfterEnv": ["./jest.setup.ts"]
  }
```

(similar for pure JS)
