### ISSUE TITLE
Trouble persisting client mock when isolating other modules

### ISSUE THREAD

**Issue by glhrmv** [m-radzikowski/aws-sdk-client-mock#179]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Hi all, I'm running into an issue mocking an SDK client (DynamoDB) across several tests. 

I have placed a minimally reproducible example below. 

There are two tests attached, and each test essentially calls a Lambda that depends on a set of constants (`TEST_1` and `TEST_2`) and on a DynamoDB client. The difference between the two tests is that the values of the constants mocked are different, as you can see quite clearly.

When I run each of these 2 tests solo, they both pass individually. However, when I run the tests sequentially in the same execution (usually test 1 followed by test 2) then the second test fails because of the object equality assertions:

```
Expected: "newtest1"
Received: "test1"

> 53 |     expect(result.TEST_1).toBe('newtest1');
```

What I gather here is that Jest seems to retain the mocked constants from test 1 and is not overwriting them in test 2. 

At this point, I have tried a few approaches to fix this: essentially, I want both the dependency modules (the constants and the SDK client) to be mocked "from scratch" on each test. What got me the farthest was **wrapping each of the test bodies inside `jest.isolateModules()` function blocks**. 

However, I did not include this in the reproducible example because this actually seems like a more problematic state than before: while the 2 tests seem to "pass", after their execution the console prints strange validation exceptions thrown and when I debug each test, I see they actually fail in the `dynamoDbClient.send()` calls -- I think the DynamoDB client mock is not being used here and it's actually using the real client instance. Somehow, though, Jest still marks the tests as passed.

Am I doing something wrong? I suspect I need a `jest.resetModules()` somewhere but nothing I've tried gets me closer to what I want.

### Reproduction

src/lambda-test.js:

```js
'use strict';

const { QueryCommand } = require('@aws-sdk/client-dynamodb');
const { TEST_1, TEST_2 } = require('./constants');
const { dynamoDbClient } = require('./clients/dynamodb');

exports.handler = async (event) => {
  console.log(event);
  await dynamoDbClient.send(
    new QueryCommand({
      TableName: 'abc',
    }),
  );
  return { TEST_1, TEST_2 };
};
```

src/clients/dynamodb.js:

```js
'use strict';

const { DynamoDBDocumentClient } = require('@aws-sdk/lib-dynamodb');
const { DynamoDBClient } = require('@aws-sdk/client-dynamodb');

const { AWS_REGION } = process.env;

const dynamoDbClient = DynamoDBDocumentClient.from(
  new DynamoDBClient({
    region: AWS_REGION,
  }),
);

module.exports = { dynamoDbClient };
```

src/constants/index.js
```js
'use strict';

module.exports = {
  TEST_1: process.env.TEST_1,
  TEST_2: process.env.TEST_2
};
```

test/unit/lambda-test.test.js:

```js
'use strict';

const { QueryCommand } = require('@aws-sdk/client-dynamodb');

const { dynamoDbMock } = require('../__mocks__/dynamodb');

describe('Lambda Test', () => {
  let handler;

  beforeEach(() => {
    jest.resetAllMocks();
    dynamoDbMock.reset();
  });

  afterAll(() => {
    dynamoDbMock.restore();
  });

  test('1', async () => {
    jest.doMock('../../src/constants', () => {
      return {
        ...jest.requireActual('../../src/constants'),
        TEST_1: 'test1',
        TEST_2: 'test2',
      };
    });

    ({ handler } = require('../../src/lambda-test'));

    dynamoDbMock.on(QueryCommand).resolvesOnce({});
    const result = await handler({});

    expect(dynamoDbMock).toHaveReceivedCommand(QueryCommand);
    expect(result.TEST_1).toBe('test1');
    expect(result.TEST_2).toBe('test2');
  });

  test('2', async () => {
    jest.doMock('../../src/constants', () => {
      return {
        ...jest.requireActual('../../src/constants'),
        TEST_1: 'newtest1'
        TEST_2: 'newtest2',
      };
    });

    ({ handler } = require('../../src/lambda-test'));

    dynamoDbMock.on(QueryCommand).resolvesOnce({});
    const result = await handler({});

    expect(dynamoDbMock).toHaveReceivedCommand(QueryCommand);
    expect(result.TEST_1).toBe('newtest1');
    expect(result.TEST_2)toBe('newtest2');
  });
});
```

test/\_\_mocks\_\_/dynamodb.js:

```js
'use strict';

const { mockClient } = require('aws-sdk-client-mock');
const { dynamoDbClient } = require('../../src/clients/dynamodb');

const dynamoDbMock = mockClient(dynamoDbClient);

module.exports = {
  dynamoDbMock,
};
```

### Environment

- Node version: v16.20.0
- Testing lib and version: Jest 29.0.3
- Typescript version: N/A
- AWS SDK v3 Client mock version: 3.0.0
- AWS JS SDK libs and versions:
  - "@aws-sdk/client-dynamodb": "^3.370.0"
  - "@aws-sdk/lib-dynamodb": "^3.370.0",

**Comment by bauer01** [comment]
Hi @glhrmv 
I had similar problem but resolved with AWS SDK downgrade to version `"@aws-sdk/client-dynamodb": "^3.363.0",`
