### ISSUE TITLE
Client creation test

### ISSUE THREAD

**Issue by kristiannotari** [m-radzikowski/aws-sdk-client-mock#18]
When mocking an aws client I would like to be able to also test the configuration given to the client during initialization.

Assume I have a util function:

```typescript
export const myFunction = async (config: S3ClientConfig) => {
    const client = new S3Client(config)
    await client.send( ... )
}
```

And in my test I have:

```typescript
describe('myFunction', () => {
    it('should create a s3 client with given configuration and send ...', () => {
        const s3mock = mockClient(S3Client)
        const myConfig = { ... }

        await expect(myFunction(myConfig)).resolves.toBeUndefined()
        expect(s3mock.calls()).toHaveLength(1)

        // here I would also like to test if the config given to the s3 client is exactly the one 
        // I gave to myFunction call as parameter
    })
})
```

Is there already a way to achieve this?

**Comment by m-radzikowski** [comment]
Hey,
no, it's not possible at the moment. I will leave this issue open to support returning the Client's config in the future.

**Comment by m-radzikowski** [comment]
I was thinking about this a little bit more.

Firstly, the lib mocks only a `send()` message. Apart from that, it does not interfere with how the client is constructed, how it works, etc.
Moreover, in this case, client creation is inner implementation.

But on the positive news - since we are testing the command send method, we should be able to get everything that is related to this call. And we are - see this example on how to get a region used in the call:

```typescript
export const myFunction = async () => {
    const client = new SNSClient({region: 'eu-west-2'});
    await client.send(new ListTopicsCommand({}));
};

it('check region', async () => {
    const mock = mockClient(SNSClient);

    await myFunction();

    const call = mock.calls()[0];
    const region = call.thisValue.config.region() as Promise<string>;
    await expect(region).resolves.toBe('eu-west-2');
});
```

Debug `mock.calls()[0]` to find other params passed when sending the command.

**Comment by kristiannotari** [comment]
You're right. The goal here is to mock the send method and this mocking library does that greatly. Also, as you noted, you can test whatever configuration is used during the send method, limited only by the information exposed during the send method itself. 

However, this is not the same as checking if the client has been initialized with a specific configuration or how the configuration changed over time based on some other behaviour but it's testing the configuration during the call (tell me if I'm wrong, I'm not an expert with sinonjs), or the configuration after all the calls if that's something behind a reference.

But I think proper client initialization testing should be moved to its own separate mocking experience or be an "opt-in/out" setting instead of just changing how the current mockClient works just to satisfy the need.
