### ISSUE TITLE
Customise mock response based on client region

### ISSUE THREAD

**Issue by joshbalfour** [m-radzikowski/aws-sdk-client-mock#181]
Hiya,

First off - HUGE fan of this library, it's super helpful and easy to use!!

One thing that could be cool is the ability to know which region the Client was instantiated in.

My simplest use case for this is I have a custom resource which replicates a KMS key across multiple regions. 
Before it sends the ReplicateKeyCommand it sends a DescribeKey in the replication region, to see if there is a key with the same ID which is pending deletion. So I would like to customise the response it gives based on the command + region, rather than just the command.

If you think this would be a good idea, I'll send a PR your way.

Thanks!

**Comment by m-radzikowski** [comment]
Hey, here is an example on how to achieve it using `callsFake()`:

https://github.com/m-radzikowski/aws-sdk-client-mock/blob/06254dd2c0432a1b35b2f7d986df5c30fe647b55/packages/aws-sdk-client-mock/test/mockClient.test.ts#L657-L680
