### ISSUE TITLE
paginate functions from @aws-sdk/lib-dynamodb throw invalid client error

### ISSUE THREAD

**Issue by JavierLuna** [m-radzikowski/aws-sdk-client-mock#182]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

When trying to use a mocked document client with a `paginate` function (e.g `paginateQuery`), the function throws the following: `Invalid client, expected DynamoDBDocument | DynamoDBDocumentClient` ([src](https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-dynamodb/src/pagination/QueryPaginator.ts#L59))

When the document client mocking feature [was added](https://github.com/m-radzikowski/aws-sdk-client-mock/pull/11/commits/8271c731579a0fbe33051e1d1d1eb6cc6047e516), it seems like the tests were still using the `paginateQuery` function from `@aws-sdk/client-dynamodb` instead of `@aws-sdk/lib-dynamodb`.

### Reproduction

import { 
  paginateQuery,
} from "@aws-sdk/lib-dynamodb";

const mockDDB = mockClient(DynamoDBDocumentClient.from(new DynamoDBClient()));

for await (const page of paginateQuery({client: mockDDB}, {} as any)) {
  console.log(page); // wont arrive here
} 

### Environment

- Node version: v18.17.1
- Testing lib and version: jest 27.4.7
- Typescript version: 4.9.3
- AWS SDK v3 Client mock version: 3.0.0
- AWS JS SDK libs and versions: `lib-dynamodb` and `client-dynamodb` 3.391.0

**Comment by samchungy** [comment]
I believe you're meant to mock the class rather than the return from .from().

eg. `mockClient(DynamoDBDocumentClient)`;

and then create your client as you normally do

**Comment by JavierLuna** [comment]
As I understood from [the docs](https://m-radzikowski.github.io/aws-sdk-client-mock/#mock), mocking a class mocks all instances of said client, mocking the instance is just scoped to that specific instance. I want to scope it down to the instance.

That aside, I don't think it'll make a difference, as the mock is still not a subclass of `DynamoDBDocumentClient`, and that's a check that `paginateQuery` does (see my issue description)

**Comment by m-radzikowski** [comment]
You can mock both `DynamoDBClient` and `DynamoDBDocumentClient`. Paginated operations are really just sending the regular Commands under the hood, so you can mock them as [described in the README](https://github.com/m-radzikowski/aws-sdk-client-mock?tab=readme-ov-file#paginated-operations). One note is that pagination functions, like `paginateQuery`, must receive the real AWS SDK Client / DocumentClient, not the mock - just like in the regular code.

This works fine:

```ts
import {DynamoDBClient} from '@aws-sdk/client-dynamodb';
import {DynamoDBDocumentClient, paginateQuery, QueryCommand} from '@aws-sdk/lib-dynamodb';

it('mocks DocumentClient paginated operation', async () => {
    const mock = mockClient(DynamoDBDocumentClient);
    mock.on(QueryCommand, {TableName: 'mock', ExclusiveStartKey: undefined, Limit: 1}).resolves({
        Items: [
            {pk: 'a', sk: 'b'},
        ],
        LastEvaluatedKey: {pk: 'a', sk: 'b'},
    }).on(QueryCommand, {TableName: 'mock', ExclusiveStartKey: {pk: 'a', sk: 'b'}, Limit: 1}).resolves({
        Items: [
            {pk: 'c', sk: 'd'},
        ],
    });

    const dynamodb = new DynamoDBClient({});
    const ddb = DynamoDBDocumentClient.from(dynamodb);

    // note we are passing the real AWS SDK Client here, not the mock object
    const paginator = paginateQuery({client: ddb, pageSize: 1}, {TableName: 'mock'});

    const items = [];
    for await (const page of paginator) {
        items.push(...page.Items || []);
    }

    expect(items).toHaveLength(2);
    expect(items?.[1]).toStrictEqual({pk: 'c', sk: 'd'});
});
```

Please reopen if something is not clear or does not work.
