### ISSUE TITLE
Type incompatibility introduced from aws-sdk-js-v3@3.378.0

### ISSUE THREAD

**Issue by jameshopkins** [m-radzikowski/aws-sdk-client-mock#185]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Since upgrading `@aws-sdk/*` to > v3.378.0, I'm getting the type issue below using a client. For example, for Personalize:

```
Error: index.test.ts(12,36): error TS2345: Argument of type 'typeof PersonalizeEventsClient' is not assignable to parameter of type 'InstanceOrClassType<Client<ServiceInputTypes, MetadataBearer, SmithyResolvedConfiguration<HttpHandlerOptions>>>'.
  Type 'typeof PersonalizeEventsClient' is not assignable to type 'ClassType<Client<ServiceInputTypes, MetadataBearer, SmithyResolvedConfiguration<HttpHandlerOptions>>>'.
    The types of 'prototype.middlewareStack.concat' are incompatible between these types.
      Type '<InputType extends ServiceInputTypes, OutputType extends ServiceOutputTypes>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<...>' is not assignable to type '<InputType extends ServiceInputTypes, OutputType extends MetadataBearer>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<InputType, OutputType>'.
        Types of parameters 'from' and 'from' are incompatible.
          Type 'MiddlewareStack<InputType, OutputType>' is not assignable to type 'MiddlewareStack<InputType, ServiceOutputTypes>'.
            Types of property 'addRelativeTo' are incompatible.
              Type '(middleware: MiddlewareType<InputType, OutputType>, options: RelativeMiddlewareOptions) => void' is not assignable to type '(middleware: MiddlewareType<InputType, ServiceOutputTypes>, options: RelativeMiddlewareOptions) => void'.
                Types of parameters 'middleware' and 'middleware' are incompatible.
                  Type 'MiddlewareType<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                    Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                      Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'InitializeMiddleware<InputType, OutputType>'.
                        Call signature return types 'InitializeHandler<InputType, ServiceOutputTypes>' and 'InitializeHandler<InputType, OutputType>' are incompatible.
                          Type 'Promise<InitializeHandlerOutput<ServiceOutputTypes>>' is not assignable to type 'Promise<InitializeHandlerOutput<OutputType>>'.
                            Type 'InitializeHandlerOutput<ServiceOutputTypes>' is not assignable to type 'InitializeHandlerOutput<OutputType>'.
                              Types of property 'output' are incompatible.
                                Type 'ServiceOutputTypes' is not assignable to type 'OutputType'.
                                  'ServiceOutputTypes' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'MetadataBearer'.
                                    Type 'PutEventsCommandOutput' is not assignable to type 'OutputType'.
                                      'PutEventsCommandOutput' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'MetadataBearer'.
```
The issue doesn't happen when using `@aws-sdk/*@3.377.0`. I believe it _may_ be to do with AWS updating Smithy from 1 > 2 - https://github.com/aws/aws-sdk-js-v3/commit/96938415e65ccc4353be8f816e919215de12a1b7

### Reproduction

```ts
import {
  PersonalizeEventsClient,
} from "@aws-sdk/client-personalize-events";

const personalizeMock = mockClient(PersonalizeEventsClient);
```

### Environment

- Node version: 
- Testing lib and version: 
- Typescript version:
- AWS SDK v3 Client mock version: 3.0.0,
- AWS JS SDK libs and versions:
    - "@aws-sdk/client-personalize-events": "^3.370.0"

**Comment by aaron-epoxy** [comment]
I also had success using `@aws-sdk/*@3.377.0` but for my use case I need to mock an S3 response body like so:

```typescript
  const s3ClientMock = mockClient(S3Client)

  const stream = new Readable()
  stream.push(JSON.stringify({ data: true }))
  stream.push(null)

  s3ClientMock.on(GetObjectCommand).resolves({
    Body: sdkStreamMixin(stream),
  })
  ```

If anyone is using the `sdkStreamMixin` from `@aws-sdk/util-stream-node` you will also need to change to using `@smith/util-stream@2.0.12`.

**Comment by yblee85** [comment]
at the time of writing, `@aws-sdk/*@3.428.0` and getting same type mismatch error.

I was able to fix it by override (in package.json) 
```
"overrides": {
  "@smithy/types": "2.3.4"
}
```
latest version of `@smithy/types`  at this time was 2.3.5

**Comment by dannyfranca** [comment]
> ### New comment
> Please disregard this message, I reviewed my comment and it doesn't seem to be directly related to the issue of this ticket.
> 
> ### Original
> at the time of writing, latest aws-sdk version is `@aws-sdk/*@3.428.0` and getting same type mismatch error.
> 
> I was able to fix it by override (in package.json)
> 
> ```
> "overrides": {
>   "@smithy/types": "2.3.4"
> }
> ```
> 
> latest version of `@smithy/types` at this time is 2.3.5

Overriding the `@smithy/types` did the trick for me with the current latest version. I use `pnpm`, so added this to my package.json:

```
"pnpm": {
  "overrides": {
    "@smithy/types": "2.7.0"
  }
}
```

**Comment by dannyfranca** [comment]
I have sent a PR to fix this issue for the next release: https://github.com/m-radzikowski/aws-sdk-client-mock/pull/196

**Comment by m-radzikowski** [comment]
I did not get any type compatibility issues on the clean install of `@aws-sdk/*` packages in v3.378.0. The issue is, most likely, `@smithy/types` installed in multiple versions, which happens sometimes if you add/bump `@aws-sdk/*` packages.

See the [caveats section in README](https://github.com/m-radzikowski/aws-sdk-client-mock?tab=readme-ov-file#mixed-smithytypes-versions) for solution details. Overriding the `@smithy/types` version is one of the solutions listed there.

If you still have problem, please reopen the issue including the content of your `package.json` and output of `npm ls @smithy/types` / `pnpm why @smithy/types` / `yarn why @smithy/types`.
