### ISSUE TITLE
Assert constructor arguments?

### ISSUE THREAD

**Issue by mousedownmike** [m-radzikowski/aws-sdk-client-mock#186]
I have a chain of calls where I use `stsClient.send(new AssumeRoleCommand(...))` to retrieve temporary credentials that I then use to create a separate client with `new CloudFrontClient({credentials: {...}})`.

I would like to assert that the mock credentials I'm receiving from the `AssumeRoleCommand` are being properly passed to the `CloudFrontClient` constructor.  Is this possible?  

I've not used SinonJS before, maybe I need to use it directly?

**Comment by msaglietto** [comment]
I was looking for the same and the closes to validate credentials was following this comment: https://github.com/m-radzikowski/aws-sdk-client-mock/issues/144#issuecomment-1454742767
```
expect(await mockS3Client.call(0).thisValue.config.credentials()).toEqual({
            accessKeyId: ACCESS_KEY_ID,
            secretAccessKey: SECRET_ACCESS_KEY,
        });
```

**Comment by mousedownmike** [comment]
Thanks for pointing that out, @msaglietto, that works for me!
