### ISSUE TITLE
S3Client `HeadObjectCommand` doesn't work with new error handling

### ISSUE THREAD

**Issue by garysassano** [m-radzikowski/aws-sdk-client-mock#189]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

While error classes function as expected for most commands, they seem to behave differently for the `HeadObjectCommand`.

For example, I have this method:

```ts
/**
 * Check if an object exists in the bucket
 *
 * @param key Key of the object
 */
public async exists(key: string): Promise<boolean> {
  const command = new HeadObjectCommand({
    Bucket: this.bucketName,
    Key: key,
  });

  try {
    await this.s3Client.send(command);
    return true;
  } catch (error) {
    // SDK v2 approach
    if ((error as Error).name === "NotFound") {
      console.log("NotFound@v2");
    }
    // SDK v3 approach
    if (error instanceof NotFound) {
      console.log("NotFound@v3");
    }
    throw error;
  }
}
```

During my tests using the method above, the only console output I received was `NotFound@v2`, suggesting that there might be an issue.

### Environment

- Node version: v18.16.0
- Testing lib and version: Vitest v0.32.4
- Typescript version: v4.9.5
- AWS SDK v3 Client mock version: v2.2.0
- AWS JS SDK libs and versions:
    - @aws-sdk/client-s3: v3.405.0

**Comment by stern-shawn** [comment]
Hi! This came up while I was looking to mock this same operation in my own project.

```ts
if (error instanceof NotFound) {
  console.log("NotFound@v3");
}
```

I'm able to test this reliably with something like this:

```ts
const s3Client = mockClient(S3Client);
// Inside of an individual test case
s3Client.on(HeadObjectCommand).rejects(new NotFound({ message: 'sorry', $metadata: {} }));
const res = await exists(...inputs);
expect(res).toEqual(false)
```

My libraries are at these versions:
- Node: v18.16.0
- Vitest: v0.32.4
- @aws-sdk/client-s3: 3.473.0
- aws-sdk-client-mock: 3.0.0

Maybe see if upgrading the mock library to v3 fixes it for you?

**Comment by garysassano** [comment]
@stern-shawn The bug is present also in `aws-sdk-client-mock@3.0.0`

**Comment by m-radzikowski** [comment]
Like @stern-shawn wrote, if you provide a custom error object to the `rejects()` method, you will get it thrown back, so this works without an issue:

```ts
import {HeadObjectCommand, ListObjectsV2Command, NotFound, S3Client} from "@aws-sdk/client-s3";
import {mockClient} from "aws-sdk-client-mock";

const s3 = new S3Client({});
const s3Mock = mockClient(S3Client);

it('rejects with custom error', async () => {
    s3Mock.on(HeadObjectCommand).rejects(new NotFound({message: 'sorry', $metadata: {}}));

    const headObjectCommand = new HeadObjectCommand({Bucket: 'aa', Key: 'bb'});
    await expect(s3.send(headObjectCommand)).rejects.toThrow(NotFound);
});
```

If you provide just the message like `s3Mock.on(HeadObjectCommand).rejects('my message')`, you will get a standard `Error` object back with the message included.

Please provide a reproduction example if something does not work for you.
