### ISSUE TITLE
Issues with RDSClient

### ISSUE THREAD

**Issue by wayne-li2** [m-radzikowski/aws-sdk-client-mock#19]
First off, awesome project -- I'm looking forward to seeing it mature.

I created this thin RDS client wrapper as an experiment:
```
import { RDSClient } from '@aws-sdk/client-rds';

class RDSClientWrapper {
    private client: RDSClient;

    constructor(client: RDSClient) {
        this.client = client;
    }
}
```

In the testing file, I have this:
```
import { RDSClient } from '@aws-sdk/client-rds';
import { mockClient } from 'aws-sdk-client-mock';
...
describe('RDSClientWrapper', function() {
    let rdsClientWrapper: RDSClientWrapper;
    beforeEach(function() {
        const mockRDS = mockClient(RDSClient);
        rdsClientWrapper = new RDSClientWrapper(mockRDS);
    });
...
}
```

This line `rdsClientWrapper = new RDSClientWrapper(mockRDS);` errors with:

> Argument of type 'AwsStub<ServiceInputTypes, ServiceOutputTypes>' is not assignable to parameter of type 'RDSClient'.
  Type 'AwsStub<ServiceInputTypes, ServiceOutputTypes>' is missing the following properties from type 'RDSClient': config, destroy, middlewareStackts(2345)

Is extra work needed to mock the RDSClient?

**Comment by m-radzikowski** [comment]
Hey,
Thanks for the nice words. 

The problem seems to be similar to #14 - some clients have different types than most and they do not match types expected by the lib. I will try to work this out.

**Comment by wayne-li2** [comment]
Thanks for the response! I don't feel knowledgeable enough to submit my own PR, but happy to review the changes to learn if it is fixed!

**Comment by m-radzikowski** [comment]
Hey. Took me a moment but it should work now in v0.5.0, with AWS SDK v3.17.0.

Compatibility with different SDK Clients will be now checked and monitored, see [compatibility.md](https://github.com/m-radzikowski/aws-sdk-client-mock/blob/main/compatibility.md)

Please let me know in case something still doesn't work.

**Comment by wayne-li2** [comment]
Thanks!
