### ISSUE TITLE
Can I stack mock configuration in same mock instance?

### ISSUE THREAD

**Issue by yuuresuzuki** [m-radzikowski/aws-sdk-client-mock#190]
Hi. I am yuuresuzuki.

Can I stack mock configuration in same mock instance?

I would like to test a code as follow.
```
const {S3Client} = require('@aws-sdk/client-s3');
const s3 = new S3Client({});

const s3response1 = s3.send(new PutObjectCommand({
          Bucket: "test-bucket",
          Key: "test-key",
          Body: {"test":"test"},
        }));

const s3response2 = s3.send(new PutObjectCommand({
          Bucket: "test-bucket",
          Key: "test-key",
          Body: {"test":"test"},
        }));
```

I made a test as follow
```
const {S3Client} = require('@aws-sdk/client-s3');
const s3Mock = mockClient(S3Client);

s3Mock.on(PutObjectCommand).resolves({'Body': 'Body1'});
s3Mock.on(PutObjectCommand).resolves({'Body': 'Body2'});
```

I'm hoping that the first response is {'Body': 'Body1'}, and the second response is {'Body': 'Body2'}.
but both were {'Body': 'Body2'}.

I confirmed I can resolve this problem useing chained behaviors.
https://github.com/m-radzikowski/aws-sdk-client-mock#mock

But it is just example.
I try to migrate from aws sdk v2 to aws sdk v3.
Our code is built on the assumption that we can stack mock configurations using jest.spyOn.

Are there ways to stack mock configuration?

Best Regards.

**Comment by m-radzikowski** [comment]
No, this is possible only using chained behaviors, like so:

```ts
s3Mock.on(PutObjectCommand)
  .resolvesOnce({'Body': 'Body1'})
  .resolvesOnce({'Body': 'Body2'})
```
