### ISSUE TITLE
Ability pass a Sinon Sandbox

### ISSUE THREAD

**Issue by EdgarOrtegaRamirez** [m-radzikowski/aws-sdk-client-mock#192]
My project has a Sinon sandbox used to restore all stub/spies/mocks on a `afterEach` global hook.
I would like to configure `mockClient` to use it like `mockClient(Client, { sandbox: mySandbox })` or any other configuration method

**Comment by m-radzikowski** [comment]
I like the idea of having a single point of resetting all mocks.

I've added the ability in `v3.1.0-beta.0`. You can test it if you have a moment.

The API is exactly as you suggested: `mockClient(client, { sandbox: mySandbox })`
