### ISSUE TITLE
not compatible with "@aws-sdk/xxx": "3.451.0"

### ISSUE THREAD

**Issue by chejimmy** [m-radzikowski/aws-sdk-client-mock#193]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Since upgrading @aws-sdk/* to 3.451.0, I'm getting the type issue below using a client. For example, for DynamoDBClient:

```
Argument of type 'typeof DynamoDBClient' is not assignable to parameter of type 'InstanceOrClassType<Client<ServiceInputTypes, MetadataBearer, SmithyResolvedConfiguration<HttpHandlerOptions>>>'.
  Type 'typeof DynamoDBClient' is not assignable to type 'ClassType<Client<ServiceInputTypes, MetadataBearer, SmithyResolvedConfiguration<HttpHandlerOptions>>>'.
    The types of 'prototype.middlewareStack.concat' are incompatible between these types.
      Type '<InputType extends ServiceInputTypes, OutputType extends ServiceOutputTypes>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<...>' is not assignable to type '<InputType extends ServiceInputTypes, OutputType extends MetadataBearer>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<InputType, OutputType>'.
        Types of parameters 'from' and 'from' are incompatible.
          Type 'MiddlewareStack<InputType, OutputType>' is not assignable to type 'MiddlewareStack<InputType, ServiceOutputTypes>'.
            Types of property 'addRelativeTo' are incompatible.
              Type '(middleware: MiddlewareType<InputType, OutputType>, options: RelativeMiddlewareOptions) => void' is not assignable to type '(middleware: MiddlewareType<InputType, ServiceOutputTypes>, options: RelativeMiddlewareOptions) => void'.
                Types of parameters 'middleware' and 'middleware' are incompatible.
                  Type 'MiddlewareType<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                    Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                      Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'InitializeMiddleware<InputType, OutputType>'.
                        Call signature return types 'InitializeHandler<InputType, ServiceOutputTypes>' and 'InitializeHandler<InputType, OutputType>' are incompatible.
                          Type 'Promise<InitializeHandlerOutput<ServiceOutputTypes>>' is not assignable to type 'Promise<InitializeHandlerOutput<OutputType>>'.
                            Type 'InitializeHandlerOutput<ServiceOutputTypes>' is not assignable to type 'InitializeHandlerOutput<OutputType>'.
                              Types of property 'output' are incompatible.
                                Type 'ServiceOutputTypes' is not assignable to type 'OutputType'.
                                  'ServiceOutputTypes' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'MetadataBearer'.
                                    Type 'BatchExecuteStatementCommandOutput' is not assignable to type 'OutputType'.
                                      'BatchExecuteStatementCommandOutput' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'MetadataBearer'.
```

The issue doesn't happen when using @aws-sdk/*@3.450.0. I believe it may be to do with AWS updating Smithy
- [feat(experimentalIdentityAndAuth): release phase for `@smithy.api#htt…](https://github.com/aws/aws-sdk-js-v3/commit/2e1ac5bfe9be91291cdee27487b5bd99aa120fdd)
- [chore(codegen): update smithy-typescript commit (](https://github.com/aws/aws-sdk-js-v3/commit/6bd28f1d3992fb4db76a1a6db66fca7f33504d60)

### Reproduction

```
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';

const ddbMock = mockClient(DynamoDBClient);
```

### Environment

- Node version: 18.14.0
- Testing lib and version: "jest": "29.5.0"
- Typescript version: "typescript": "^5.2.2"
- AWS SDK v3 Client mock version: "aws-sdk-client-mock": "^3.0.0"
- AWS JS SDK libs and versions: 
    "@aws-sdk/client-cloudwatch": "3.451.0",
    "@aws-sdk/client-cloudwatch-logs": "3.451.0",
    "@aws-sdk/client-iot-events": "3.451.0",
    "@aws-sdk/client-iotsitewise": "3.451.0",
    "@aws-sdk/credential-providers": "3.451.0",
    "@aws-sdk/client-dynamodb": "3.451.0",
    "@aws-sdk/lib-dynamodb": "3.451.0",

**Comment by chejimmy** [comment]
Found another issue with similar bug behavior https://github.com/m-radzikowski/aws-sdk-client-mock/issues/185
however, the other issue is with v3.378.0 and this one with v3.451.0

**Comment by AminFazlMondo** [comment]
Is there any solution for this bug?

**Comment by AminFazlMondo** [comment]
> Is there any solution for this bug?

It is fixed for me now with the later versions.
Thanks

**Comment by ibrahimqasim-abtrace** [comment]
Getting this issue with "@aws-sdk/client-secrets-manager": "^3.477.0"

**Comment by dannyfranca** [comment]
I have sent a PR to fix this issue for the next release: https://github.com/m-radzikowski/aws-sdk-client-mock/pull/196

**Comment by m-radzikowski** [comment]
I did not get any type compatibility issues on the clean install of `@aws-sdk/*` packages in v3.451.0. The issue is, most likely, `@smithy/types` installed in multiple versions, which happens sometimes if you add/bump `@aws-sdk/*` packages. See the [caveats section in README](https://github.com/m-radzikowski/aws-sdk-client-mock?tab=readme-ov-file#mixed-smithytypes-versions) for solution details. If you still have problem, please reopen the issue including the content of your `package.json` and output of `npm ls @smithy/types` / `pnpm why @smithy/types` / `yarn why @smithy/types`.
