### ISSUE TITLE
Invalid import in AWS Lambda Example

### ISSUE THREAD

**Issue by ryansonshine** [m-radzikowski/aws-sdk-client-mock#20]
The [example in the readme](https://github.com/m-radzikowski/aws-sdk-client-mock/blame/main/README.md#L302) for importing the client is currently:

```ts
import { mockClient } from '@m-radzikowski/aws-sdk-client-mock';
```

I believe it should be:

```ts
import { mockClient } from 'aws-sdk-client-mock';
```

**Comment by m-radzikowski** [comment]
Oh, right. Some "find and replace" gone wrong. Thanks for the PR!
