### ISSUE TITLE
Support `toHaveReceivedAnyCommand`

### ISSUE THREAD

**Issue by yaronya** [m-radzikowski/aws-sdk-client-mock#201]
I'm migrating my Node.js AWS SDK v2 codebase to v3.
I'm using `jest` as my testing framework, and sometimes I have a long test matrix that accepts the relevant `Command` used as a parameter. The test matrix also supports a scenario where the `Command` is irrelevant, and therefore is `undefined`.

When I run `.not.toHaveReceivedCommandWith(undefined)` the code crashes, as it expects a valid `Command`.
I wish I was able to just `.not.toHaveReceivedAnyCommand` to settle this specific use-case. It's also a common matcher pattern in other popular custom matchers, like `jest-extended`

I'm not that familiar with the jest matchers framework, but willing to contribute if this makes sense :)

**Comment by m-radzikowski** [comment]
Sure, if you want to contribute, please make a PR with this matcher.

In the meantime, you can achieve this with:

```ts
expect(clientMock.calls()).toBeGreaterThan(0);
```

Just remember to reset the mocks every test (`clientMock.reset()` or `clientMock.resetHistory()` in `beforeEach` / `afterEach` block).

I agree having a `toHaveReceivedAnyCommand()` matcher would be nice and more readable :)
