### ISSUE TITLE
Add repository object/homepage key to package.json

### ISSUE THREAD

**Issue by JaredAAT** [m-radzikowski/aws-sdk-client-mock#203]
Please Add a repository object or homepage key to your package.json so that i can quickly get to the packages homepage from within vscode.  As you can see in the 2 screenshots, this package does not have a link generated, whereas **jasmine-spec-reporter** does

![Screenshot 2024-01-05 at 11 54 21](https://github.com/m-radzikowski/aws-sdk-client-mock/assets/79908660/88c64a31-bd00-4374-80d6-2fd282bd0880)

![Screenshot 2024-01-05 at 11 55 53](https://github.com/m-radzikowski/aws-sdk-client-mock/assets/79908660/95e4bee5-f9dd-4ab0-a7cb-731c9c7a0de8)

The **jasmine-spec-reporter** package.json looks like this:

```
"homepage": "https://github.com/bcaudan/jasmine-spec-reporter",
"repository": {
    "type": "git",
    "url": "https://github.com/bcaudan/jasmine-spec-reporter"
  }
```

**Comment by m-radzikowski** [comment]
Good point, please feel free to submit a PR. Otherwise, I will do this when I have a free moment, but I'm traveling right now.

**Comment by m-radzikowski** [comment]
Done, in v3.1.0 you should see the link to the homepage.
