### ISSUE TITLE
Fail to stub entirely QueryCommand - DynamoDB

### ISSUE THREAD

**Issue by SteveAldrin** [m-radzikowski/aws-sdk-client-mock#204]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Hi there,

I'm strungling with some tests, I only succeed to resolve with "anyCommand", with on("QueryCommand") it doesn't work.
I've had no problems with other clients.

Any clue or idea to resolve this ?

ps: I also tried to reject but in the same way, I was not surprised I didn't work.

### Reproduction

        const { QueryCommand } = require('@aws-sdk/lib-dynamodb');

        beforeEach(() => {
            dynamoDBMock = mockClient(globalDynamoDBDocumentClient);
        });
        it.only('should work with type and year 2021', async function () {
            // dynamoDBMock.onAnyCommand().resolves(fakeDAO.entityLow.queryResult);  // resolves rightly
            dynamoDBMock.on(QueryCommand).resolves(fakeDAO.entityLow.queryResult); // resolves undefined 

            await StockService.getStockTransfers('BL', '2021') // -> call of DynamoDBDocumentClient.send(new QueryCommand(awsParams)
            dynamoDBMock.commandCalls(QueryCommand);
        });
        
        
        

### Environment

- Node version: v18.18.0
- Testing lib and version: Mocha 10.2.0
- Typescript version: 5.2.2
- AWS SDK v3 Client mock version: 3.0.1
- AWS JS SDK libs and versions:
    - "@aws-sdk/client-dynamodb": "^3.485.0",
    -"@aws-sdk/lib-dynamodb": "^3.485.0"

**Comment by m-radzikowski** [comment]
Hey, please provide a [minimal reproductible example](https://stackoverflow.com/help/minimal-reproducible-example) that includes all the code needed to run the test (like creating the client instance and sending the command).
