### ISSUE TITLE
Types is not working for aws-sdk 3.362.0

### ISSUE THREAD

**Issue by akaNightmare** [m-radzikowski/aws-sdk-client-mock#207]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Hello, have a PNPM monorepo and one of package have dependencies like
```json
"dependencies": {
  "@aws-sdk/client-ssm": "3.362.0"
},
"devDependencies": {
  "@smithy/types": "1.1.0",
  "aws-sdk-client-mock": "^2.2.0"
},
```
Received an error like
<img width="946" alt="image" src="https://github.com/m-radzikowski/aws-sdk-client-mock/assets/4151616/80a17373-c3ee-4d26-8786-f579a3f17dc3">

### Reproduction

```ts
import { SSM } from '@aws-sdk/client-ssm';
import { mockClient } from 'aws-sdk-client-mock';

const ssmClientMock = mockClient(SSM);
```

### Environment

- Node version: v18.18.2
- Testing lib and version: Jest v29.7.0
- Typescript version: v5.0.x
- AWS SDK v3 Client mock version: v2.2.0
- AWS JS SDK libs and versions: @aws-sdk/client-ssm v3.362.0

**Comment by wweaver** [comment]
https://github.com/aws/aws-sdk-js-v3/issues/5252

**Comment by wweaver** [comment]
I think I resolved it by making sure all `@aws-sdk` packages were up to date. I had the one I was working with (@aws-sdk/client-s3) updated but I had another one that was added for a different area of the project that had an older version (@aws-sdk/util-stream-node)

**Comment by ltbittner** [comment]
+1 I am seeing this issue also. Using latest version of all packages

**Comment by m-radzikowski** [comment]
The `Client` type in the AWS SDK up to v3.363.0 was defined in the `@aws-sdk/types` package. From v3.363.0, the `Client` type is in `@smithy/types`. So having installed v3.362.0 and `@smithy/types` most likely leads to type conflicts.

Updating all AWS SDK packages to the same version and making sure only one version of `@aws-sdk/types` or `@smithy/types` is installed usually solves problems. See [README](https://github.com/m-radzikowski/aws-sdk-client-mock?tab=readme-ov-file#mixed-smithytypes-versions) and #197.
