### ISSUE TITLE
AwsStub issues

### ISSUE THREAD

**Issue by paul-uz** [m-radzikowski/aws-sdk-client-mock#208]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Using the latest AWS SDK packages (3.496.0) and latest mock version (3.0.1) I am seeing this error:

```
Type 'AwsStub<ServiceInputTypes, ServiceOutputTypes, DynamoDBClientResolvedConfig>' is missing the following properties from type 'DynamoDBClient': config, destroy, getDefaultHttpAuthSchemeParametersProvider, getIdentityProviderConfigProvider, middlewareStackts(2739)
```

I checked the smithy types, and I have mostly 2.9.1 but one AWS package, node-http-handler, uses 1.2.0. I installed the types as a dev dependency, but that didn't help.

### Reproduction

* Install @aws-sdk/* 3.496.0
* Install aws-sdk-client-mock 3.0.1
* mock client eg `const foo = mockClient(new S3Client({ region: 'eu-west-1' })`
* See TS errors when passing mocked client to a method that accepts an S3Client type

### Environment

- Node version: 18
- Testing lib and version: Jest
- Typescript version: 4.9.5
- AWS SDK v3 Client mock version: 3.0.1
- AWS JS SDK libs and versions:
    "@aws-sdk/client-dynamodb": "^3.496.0",
    "@aws-sdk/client-firehose": "^3.496.0",
    "@aws-sdk/client-kinesis": "^3.496.0",
    "@aws-sdk/client-lambda": "^3.496.0",
    "@aws-sdk/client-s3": "^3.496.0",
    "@aws-sdk/util-dynamodb": "^3.496.0",
    "@smithy/node-http-handler": "^2.3.1",
    "@smithy/protocol-http": "^3.1.1",

EDIT - updated AWs package list

**Comment by paul-uz** [comment]
So `@aws-sdk/node-http-handler` is deprecated, moving to `@smithy/node-http-handler` so I fixed that, now all smithy types are 2.9.1. But I still have the AwsStub error.

**Comment by m-radzikowski** [comment]
Hey. Creating a fresh project with provided dependencies does not give me any type errors. After changing versions from `^3.496.0` to `3.496.0` to install exactly those packages also no errors.

Please try installing the latest AWS SDK packages and following steps described in #197. You can also try removing `package-lock.json` to resolve fresh versions of all dependencies. If nothing helps, please create a new repository with problem reproduction and reopen this issue.

**Comment by paul-uz** [comment]
I'll have to recheck as we recently moved to node20 and updated pretty much everything
