### ISSUE TITLE
Question: how to list/print configured client beheviours?

### ISSUE THREAD

**Issue by fauxbytes** [m-radzikowski/aws-sdk-client-mock#214]
Hi. Given a mock configured with a set behaviours:
```
export const mock = mockClient(DynamoDBDocumentClient)
    .on(PutCommand).resolves({})
    //... etc
```

How can this configuration be printed-out (e.g. for the purpose of troubleshooting the mock's behaviour)?
Thank you.

**Comment by m-radzikowski** [comment]
Hey. This is not possible and, frankly, unlikely to be implemented. Under the hood, mocks use the Sinon.JS library, which also does not have such an ability.
