### ISSUE TITLE
Jest matcher expect().toEqual() throws error "TypeError: this.customTesters is not iterable"

### ISSUE THREAD

**Issue by gborobio73** [m-radzikowski/aws-sdk-client-mock#219]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Thanks a lot for this library 🙏 

Jest matcher expect().toEqual() throws an error "TypeError: this.customTesters is not iterable". I'm not sure if this is the intended behavior.

### Reproduction

```JS
// test.spec.ts
import 'aws-sdk-client-mock-jest';

it('test', () => {
  expect({ a: 'a' }).toEqual({ a: 'a' });
});

```
Running this test results in:
```
✕ test (5 ms)

  ● test

    TypeError: this.customTesters is not iterable

      2 |
      3 | it('test', () => {
    > 4 |   expect({ a: 'a' }).toEqual({ a: 'a' });
        |                      ^
      5 | });
      6 |
```
If I remove the `import` everything works as expected.

Thanks a lot!

### Environment

- Node version: v18.16.0
- Testing lib and version: 
    Jest "^28.0.3"
    "ts-node": "^10.7.0"
    "ts-jest": "^28.0.1"
- Typescript version:
    "typescript": "^4.6.4"
- AWS SDK v3 Client mock version: 
    "aws-sdk-client-mock": "^4.0.0",
    "aws-sdk-client-mock-jest": "^4.0.0",
- AWS JS SDK libs and versions:

**Comment by alexander-cox** [comment]
I had an almost identical issue to this but I found that if I bumped the versions of jest and ts-jest to versions ^v29 it resolved itself

**Comment by gborobio73** [comment]
> I had an almost identical issue to this but I found that if I bumped the versions of jest and ts-jest to versions ^v29 it resolved itself

Ok, thanks! I'll try that 🙏

**Comment by Kairn** [comment]
In my project, I tried to replicate the same matchers file (`packages/aws-sdk-client-mock-jest/src/jestMatchers.ts`), and the same issue occurs.  

However, I changed `import {expect} from 'expect'` (this line: https://github.com/m-radzikowski/aws-sdk-client-mock/blob/main/packages/aws-sdk-client-mock-jest/src/jestMatchers.ts#L7) to `import {expect} from '@jest/globals'`, and it suddenly started to work without upgrading the library.  

Not sure why, but this was the import used in the Jest documentation too (https://jestjs.io/docs/expect#expectextendmatchers). Maybe consider making this change as a fix.

**Comment by m-radzikowski** [comment]
Using `@jest/globals` types works with Jest 29.

Using `@types/jest` works with both Jest 28 and 29.

See more on Jest types: https://jestjs.io/docs/getting-started#using-typescript

If there is still a problem using this setup, please reopen providing reproduction example and exact package versions.
