### ISSUE TITLE
Move @types/sinon to prod dependencies

### ISSUE THREAD

**Issue by claabs** [m-radzikowski/aws-sdk-client-mock#22]
Building with Typescript on a project that doesn't already use sinon throws this error:
```
node_modules/aws-sdk-client-mock/dist/types/awsClientStub.d.ts:2:41 - error TS7016: Could not find a declaration file for module 'sinon'. '<my-project>/node_modules/sinon/lib/sinon.js' implicitly has an 'any' type.
  Try `npm install @types/sinon` if it exists or add a new declaration (.d.ts) file containing `declare module 'sinon';`

2 import { SinonSpyCall, SinonStub } from 'sinon';
                                          ~~~~~~~

```

The [Typescript handbook recommends](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies) that any exported type that has a dependency on a package should be in the `dependencies` rather than `devDependencies`. Moving `@types/sinon` to the `dependencies` would solve this issue.

**Comment by m-radzikowski** [comment]
Thank you for the link to the docs, didn't know about it. Should be OK now in v0.5.0.
