### ISSUE TITLE
Documentation for callsFake() should provide an example of returning Promise.reject()

### ISSUE THREAD

**Issue by ahammond** [m-radzikowski/aws-sdk-client-mock#221]
The way to have a fake reject instead of resolve is to have `callsFake()` return a `Promise.reject()`. It's super simple and elegant... and it took me asking ChatGPT to figure it out. I think it would make sense to add an example to to docs which shows this.

**Comment by m-radzikowski** [comment]
Hey,
in README there is this example:

```ts
snsMock
    .callsFake(input => {
        if (input.Message === 'My message') {
            return {MessageId: '12345678-1111-2222-3333-111122223333'};
        } else {
            throw new Error('mocked rejection');
        }
    });
```

This is the correct way of throwing an error from the `callsFake()` as the resulting error resembles the SDK one more closely.

That being said, I've added code examples in JSDoc to all mock functions, including the one above. Thank you for bringing it to my attention.
