### ISSUE TITLE
sinon v11 broke sinon.match assertions on your mock

### ISSUE THREAD

**Issue by m-ronchi** [m-radzikowski/aws-sdk-client-mock#24]
your package depends on `sinon` v9, that depends on `@sinonjs/samsam` v5 (the package used to implement matchers)

sinon released v11 that depends on @sinonjs/samsam v6.
installing sinon v11 in my project together with aws-sdk-client-mock results in duplicates of both packages installed, thus breaking tests with assertions like this:

```
sinon.assert.calledWithExactly(s3mock.send, sinon.match.any)
```

you should either:
- upgrade to sinon v11
- move sinon to peer dependencies to not duplicate it
- expose `sinon.match*` through your package

**Comment by m-radzikowski** [comment]
Thanks for the info. I've updated Sinon to v11 in the latest v0.5.0.

I think peer dependencies would not work here as the lib uses Sinon itself.
I don't want to expose matchers by myself to allow easy usage with regular Sinon. But I will reconsider if it will be a problem in the future.

**Comment by m-ronchi** [comment]
this broke again with sinon@13

**Comment by m-ronchi** [comment]
sorry, it turned out that `@aws-sdk/lib-storage` changed the underlying calls from `MultipartUpload` to `PutObject` when I upgraded (a minor) and at the time I found duplicated sinon v11/v13 in my node_modules.

the error message was confusing AF
