### ISSUE TITLE
Add commandCall method

### ISSUE THREAD

**Issue by icholy** [m-radzikowski/aws-sdk-client-mock#240]
I'd like a `commandCall` method which behaves similar to the `call` method. It would return a specific index of a command.

### Signature:

``` ts
/**
 * Returns n-th call of given Command only.
 * @param n Index of the call
 * @param commandType Command type to match
 * @param input Command payload to match
 * @param strict Should the payload match strictly (default false, will match if all defined payload properties match)
 */
commandCall<TCmd extends AwsCommand<any, any>,
    TCmdInput extends TCmd extends AwsCommand<infer TIn, any> ? TIn : never,
    TCmdOutput extends TCmd extends AwsCommand<any, infer TOut> ? TOut : never,
>(
    n: number,
    commandType: new (input: TCmdInput) => TCmd,
    input?: Partial<TCmdInput>,
    strict?: boolean,
): SinonSpyCall<[TCmd], Promise<TCmdOutput>>;
```

### Example

I have code like this:

``` ts
const scanCalls = mock.commandCalls(ScanCommand);
expect(scanCalls).lengthOf(2);
scanCalls[0].calledWithMatch({
	input: { TableName: 'TestTable' },
});
scanCalls[1].calledWithMatch({
	input: { TableName: 'TestTable', ExclusiveStartKey: { id: '2' } },
});
const batchWriteCalls = mock.commandCalls(BatchWriteCommand);
expect(batchWriteCalls).lengthOf(2);
batchWriteCalls[0].calledWithMatch({
	input: {
		RequestItems: {
			TestTable: [{ PutRequest: { Item: { id: '1', _et: 'THING' } } }],
		},
	},
});
batchWriteCalls[1].calledWithMatch({
	input: {
		RequestItems: {
			TestTable: [{ PutRequest: { Item: { id: '3', _et: 'THING' } } }],
		},
	},
});
```

I'd like to write it like this:

``` ts
mock.commandCall(0, ScanCommand).calledWithMatch({ input: { TableName: 'TestTable' } });
mock.commandCall(1, ScanCommand).calledWithMatch({
	input: { TableName: 'TestTable', ExclusiveStartKey: { id: '2' } },
});
mock.commandCall(0, BatchWriteCommand).calledWithMatch({
	input: {
		RequestItems: {
			TestTable: [{ PutRequest: { Item: { id: '1', _et: 'THING' } } }],
		},
	},
});
mock.commandCall(1, BatchWriteCommand).calledWithMatch({
	input: {
		RequestItems: {
			TestTable: [{ PutRequest: { Item: { id: '3', _et: 'THING' } } }],
		},
	},
});
```

**Comment by m-radzikowski** [comment]
Looks like a nice readability improvement. I would change the order to have the number first:

```ts
mock.commandCall(0, ScanCommand)
```

to be able to pass other arguments just like in `commandCalls()` (`input` matcher and `strict` flag).

It's easy to add re-using existing `commandCalls()` method, do you want to open a PR?

**Comment by icholy** [comment]
> I would change the order to have the number first

Agreed, that's much nicer.

> It's easy to add re-using existing commandCalls() method, do you want to open a PR?

Sure, just one clarification. What should happen if there's no match? The `call` method here has a return type of `SinonSpyCall<T>`:

https://github.com/m-radzikowski/aws-sdk-client-mock/blob/3ed37a9404f5385e50dcd157f8fa6962e22452ab/packages/aws-sdk-client-mock/src/awsClientStub.ts#L105-L110

But sinon returns `null` when there's no matching call:

https://github.com/sinonjs/sinon/blob/372593f5450c5d3d54ff23f09a90e33dbc706b59/lib/sinon/proxy.js#L50

Should I do the same thing here?

**Comment by m-radzikowski** [comment]
Sinon types do not take this into account, so this may, in fact, lead to unexpected `null`. But it's convenient and it's in tests, not production code. In our case, if you do something like `return this.commandCalls(commandType)[i];`, it will return `undefined` and that's okay, I think. The return type should still be `SinonSpyCall`.

**Comment by icholy** [comment]
Sounds good to me. Do we want to stay consistent and return `null` like sinon, or is `undefined` ok?

**Comment by m-radzikowski** [comment]
On second thought, maybe throwing an error is best? You can check if that makes sense in the implementation, if not, then `null` would be best.

**Comment by icholy** [comment]
I can't take credit https://github.com/sinonjs/sinon/blob/372593f5450c5d3d54ff23f09a90e33dbc706b59/lib/sinon/proxy.js#L47
