### ISSUE TITLE
Cannot find name 'queueMicrotask'

### ISSUE THREAD

**Issue by minche-tsai** [m-radzikowski/aws-sdk-client-mock#28]
aws-sdk-client-mock v0.5.0
jest v27.0.4
TypeScript v9.1.1

```
const iotClientMock = mockClient(IoTClient);
  iotClientMock.on(DescribeJobCommand, {
    jobId: expected.job.jobId,
  }).resolves({
    job: expected.job,
  });
```

```
🤖 test » test:compile | tsc --noEmit --project tsconfig.jest.json
node_modules/@sinonjs/fake-timers/types/fake-timers-src.d.ts:11:28 - error TS2304: Cannot find name 'queueMicrotask'.

11     queueMicrotask: typeof queueMicrotask;
```

**Comment by m-radzikowski** [comment]
Hey @minche-tsai
could you share what was the problem and resolution?

**Comment by minche-tsai** [comment]
Hi @m-radzikowski 

The queueMicrotask is added in: node.js v11.0.0. But my @types/node is v10.x, so upgrade version to v15.x resolved.
Because my project is a CDK lib, it's begin by Projen. @types/nodes 10.x is initial version.
