### ISSUE TITLE
Thankyou

### ISSUE THREAD

**Issue by michael-wolfenden** [m-radzikowski/aws-sdk-client-mock#37]
Hey @m-radzikowski 

This isn't an issue. I just wanted to take the time and say thank you for creating this library. It's saved me a ton of time every single time I've worked on a project. Thankyou.

![Thankyou](https://media.giphy.com/media/fxI1G5PNC5esyNlIUs/giphy.gif)

**Comment by m-radzikowski** [comment]
Hey, I'm very glad to hear it 🙂  And honestly it feels good to see people are using something I created.

I will close this issue, but for sure will remember it 😉
