### ISSUE TITLE
Matchers returning undefined

### ISSUE THREAD

**Issue by toddpla** [m-radzikowski/aws-sdk-client-mock#38]
When adding input matchers the mocked response is `undefined`

Works
```ts
    ssmClient
      .on(GetParameterCommand)
     .resolves({ Parameter: { Value: 'something' } }
```

Doesn't work:
```ts
    ssmClient
      .on(GetParameterCommand, { Name: '/config', WithDecryption: true })
      .resolves({ Parameter: { Value: 'something' } }
```

When I log out the response for the ssm call in the application code 'something' is logged out both times.

Thanks for the awesome library!

**Comment by m-radzikowski** [comment]
Hey,
if you can clarify - if you are getting `undefined` with the second snipped, how can you get `something` logged out? It would mean the mocked parameter was resolved?

**Comment by toddpla** [comment]
@m-radzikowski this was my mistake.
The function I am testing has multiple `GetParameterCommand` calls which is why it stopped working when I provided the matcher as subsequent requests were not being matched.
Apologies for too hastily raising a ticket. Thanks again for the excellent library.
