### ISSUE TITLE
Trouble mocking Secrets Manager Client

### ISSUE THREAD

**Issue by FizzBuzz791** [m-radzikowski/aws-sdk-client-mock#44]
**Checklist**

- [x] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**

Mocking secrets manager client doesn't work as the client first tries to validate a security token which is probably not using the mocked `.send` command. Example below;

```ts
import { mockClient } from 'aws-sdk-client-mock';
import { SecretsManagerClient, GetSecretValueCommand } from '@aws-sdk/client-secrets-manager';

const smMock = mockClient(new SecretsManagerClient({}));

smMock.on(GetSecretValueCommand)
    .resolves({ 
        SecretString: JSON.stringify({ my_secret_key: 'my_secret_value' }) 
    });
```

This code throws:
> ExpiredTokenException: The security token included in the request is expired

I've tried adding a `.callsFake(() => console.log('Hit the mock'))` before the `.resolves...` method and it's not even getting that far (which supports the theory that the token validation doesn't use `send`).

**Environment**

- Node version: 16.4.1
- Typescript version: 4.3.5
- AWS SDK v3 Client mock version: 0.5.3
- AWS JS SDK libs and versions: 
  - @aws-sdk/client-secrets-manager 3.28.0

**Comment by FizzBuzz791** [comment]
Just bumping this to see if there's any ideas/updates?

**Comment by m-radzikowski** [comment]
Hey, I was vacationing so sorry for the delay, but I will look into this in the next days.

**Comment by m-radzikowski** [comment]
I run the test with both v3.28.0 and v3.34.0 of `@aws-sdk/client-secrets-manager` and it looks to work fine.

The code you posted has a slight mistake - you either pass the client **class** to the `mockClient()` function, or the same **instance** that you want to mock.

This works good for me:

```typescript
import {mockClient} from 'aws-sdk-client-mock';
import {GetSecretValueCommand, SecretsManagerClient} from '@aws-sdk/client-secrets-manager';

it('mocks SecretsManagerClient', async () => {
    const smMock = mockClient(SecretsManagerClient);
    smMock.on(GetSecretValueCommand)
        .resolves({
            SecretString: JSON.stringify({my_secret_key: 'my_secret_value'}),
        });

    const sm = new SecretsManagerClient({});
    const response = await sm.send(new GetSecretValueCommand({
        SecretId: 'qq',
    }));

    expect(response.SecretString).toBe('{"my_secret_key":"my_secret_value"}');
});
```

Alternatively, if you want to mock only a single instance of the Client, you need to provide the same instance in the mock as you use later in code:

```typescript
import {mockClient} from 'aws-sdk-client-mock';
import {GetSecretValueCommand, SecretsManagerClient} from '@aws-sdk/client-secrets-manager';

it('mocks SecretsManagerClient', async () => {
    const sm = new SecretsManagerClient({});

    const smMock = mockClient(sm);
    smMock.on(GetSecretValueCommand)
        .resolves({
            SecretString: JSON.stringify({my_secret_key: 'my_secret_value'}),
        });

    const response = await sm.send(new GetSecretValueCommand({
        SecretId: 'qq',
    }));

    expect(response.SecretString).toBe('{"my_secret_key":"my_secret_value"}');
});
```

Please let me know if that solves your problem.
