### ISSUE TITLE
Support for S3 Upload from @aws-sdk/lib-storage

### ISSUE THREAD

**Issue by ed-sparkes** [m-radzikowski/aws-sdk-client-mock#45]
[`@aws-sdk/lib-storage`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_lib_storage.html) provides an Upload capability for easy and efficient uploading of buffers, blobs, or streams, using a configurable amount of concurrency to perform multipart uploads where possible. This abstraction enables uploading large files or streams of unknown size due to the use of multipart uploads under the hood.

It is unclear if it is possible to mock this using this library, if it is please can you add to the documentation in a similar way to the dynamo document client. If it is not please can you consider adding this feature. 

Kind regards

**Comment by m-radzikowski** [comment]
I've added support for LibStorage Upload in v0.5.4, see details in the [README](https://github.com/m-radzikowski/aws-sdk-client-mock#lib-storage-upload)
