### ISSUE TITLE
Problem rejecting mocked SQSClient

### ISSUE THREAD

**Issue by skasidej** [m-radzikowski/aws-sdk-client-mock#46]
I'm trying to use rejects function, but always got an error pointing to rejects() without reason.
Does version has to be exact same as 3.18.0? My current version is 3.30.0.
<img width="1102" alt="Screen Shot 2564-09-13 at 14 11 03" src="https://user-images.githubusercontent.com/22665150/133039421-670da930-b984-49da-89aa-4a76a272f360.png">

**Comment by skasidej** [comment]
Just misunderstanding, forgot to put await at the return 🙏

**Comment by m-radzikowski** [comment]
Hey, sorry for the late reply.

No, SDK clients version does not have to be 3.18.0. But it's important that [all the AWS SDK packages are in the same version](https://github.com/m-radzikowski/aws-sdk-client-mock#mixed-aws-sdktypes-versions). Although it does not seem like an issue here.

This is an example code with a `reject()`:

```typescript
import {PublishCommand, SNSClient} from '@aws-sdk/client-sns';
import {mockClient} from 'aws-sdk-client-mock';

const publish = async (): Promise<void> => {
    const sns = new SNSClient({});
    await sns.send(new PublishCommand({
        TopicArn: '123',
        Message: 'qq',
    }));
};

it('rejects', async () => {
    const snsMock = mockClient(SNSClient);
    snsMock.on(PublishCommand).rejects();

    await expect(publish()).rejects.toThrow();
});
```

Can you test something similar to it, and provide more details about your case? Example test code that does not work would be best.

**Comment by skasidej** [comment]
@m-radzikowski I believe it's just my misunderstanding with Jest, pretty new to it. Thanks for your example, will close this thread now.

**Comment by Willis0826** [comment]
I faced this issue today. I would like to add some insights. If you faced the same issue, you may forgot to catch the exception in your code.

For example, if you wrote unit test like this, you will get the same error:

```js
import {PublishCommand, SNSClient} from '@aws-sdk/client-sns';
import {mockClient} from 'aws-sdk-client-mock';

const publish = async (): Promise<void> => {
    const sns = new SNSClient({});
    await sns.send(new PublishCommand({
        TopicArn: '123',
        Message: 'qq',
    }));
};

it('rejects', async () => {
    const snsMock = mockClient(SNSClient);
    snsMock.on(PublishCommand).rejects();

    // This is crucial! If you didn't catch the exception `publish` function threw, it showed snsMock.on(PublishCommand).rejects() has error accordingly.
    await publish();
});
```

Like Maciej mentioned, you can handle the exception in unit test with `await expect(publish()).rejects.toThrow();`

Or another potential solution is you implement a `try catch` in your code, but it depends on what you want to achieve : 

```js
import {PublishCommand, SNSClient} from '@aws-sdk/client-sns';
import {mockClient} from 'aws-sdk-client-mock';

const publish = async (): Promise<void> => {
    const sns = new SNSClient({});
    try {
        // since we catch the error here, you shouldn't see any error in your unit test.
        await sns.send(new PublishCommand({
            TopicArn: '123',
            Message: 'qq',
        }));
    } catch (err) {
        console.log('handle error here!');        
    }
};

it('rejects', async () => {
    const snsMock = mockClient(SNSClient);
    snsMock.on(PublishCommand).rejects();

    await publish();
});
```
