### ISSUE TITLE
sinon_1.stub is not a function

### ISSUE THREAD

**Issue by kylebroomfieldvariant** [m-radzikowski/aws-sdk-client-mock#52]
**Checklist**

- [x] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**

Have project setup to use Jest with ts-jest preset.

1. Used `yarn add -D aws-sdk-client-mock` to install the package to our project
2. Created a simple test to try out the mock functionality.
3. When running the test with `const sqsMock = mockClient(SQSClient)`, encountered the error `TypeError: sinon_1.stub is not a function`

Navigating to the implementation of mockClient, the import shows that `stub` is being pulled in from `sinon.ts` in the aws-sdk-client-mock package itself instead of from sinon installed in node_modules, so an error is thrown. See reference:

<img width="956" alt="aws-sdk-client-mock-wrong-import" src="https://user-images.githubusercontent.com/87319506/134073523-8331e0c8-bbbf-4a7a-b567-35520a6d9d6d.png">

The test was very simply:
```javascript
import { SQSClient } from "@aws-sdk/client-sqs";
import { mockClient } from "aws-sdk-client-mock";

describe('Simple Test', () => {
  const sqsMock = mockClient(SQSClient);

  it('should exist', () => {
    expect(true).toBeTruthy();
  });
});
```

This was tried in two different projects (both using yarn) and on several different computers, all encountered the same issue.

**Environment**

- Node version: 16.8
- Typescript version: 4.3.5
- AWS SDK v3 Client mock version: 0.5.5
- AWS JS SDK libs and versions: @aws-sdk/client-sqs v3.31.0
- Yarn 1.22.10

**Comment by kylebroomfieldvariant** [comment]
I got this working by pulling the package locally and renaming `sinon.ts` to `sinonUtils.ts`, publishing to a private registry and importing. This solved the package manager's confusion in resolving packages. I can make a PR for this change.

**Comment by m-radzikowski** [comment]
Weird, `from 'sinon'` clearly specifies a module, not a file.

I'm unable to reproduce it - even when using the same versions and environment (only Node version bumped to 16.10).

I've created this repo with a minimal setup that works for me: https://github.com/m-radzikowski/aws-sdk-client-mock-issue52
Could you try run it and tell me how it behaves in your case? Also, on what system are you? I tested on Mac (this shouldn't matter, but who knows).

**Comment by kylebroomfieldvariant** [comment]
This repo worked for me. Interesting. I'm investigating further, I'm wondering if it is an issue with our ts-config or another config file. I'll do some more investigating and report back.

**Comment by kylebroomfieldvariant** [comment]
The issue was with our `jest.config.ts`. Apparently the line `moduleDirectories: ['node_modules', './'],` is what causes the error. I copied the config with that line to the mock project and the test failed. Removing that line everything works as intended. I will close this issue. Thanks for the help!

**Comment by m-radzikowski** [comment]
Ok, glad you solved it!

**Comment by chris-feist** [comment]
I ran into the same issue but using `./src` in my `modulesDirectory` config. Instead of `./src`, I used `<rootDir>/src`

**Comment by tanato-cit** [comment]
The solution for me was to replace 

`moduleDirectories: ['node_modules', '.'],`
with
`moduleDirectories: ['node_modules', '<rootDir>'],`

Adding the full error bellow for google to index better this page.

`TypeError: (0 , sinon_1.stub) is not a function`
