### ISSUE TITLE
Support v2-style calls

### ISSUE THREAD

**Issue by m-radzikowski** [m-radzikowski/aws-sdk-client-mock#7]
The AWS SDK v3 gives an option to use it similarly to v2 SDK, with command method call instead of `send()`:

```javascript
const {DynamoDB} = require('@aws-sdk/client-dynamodb');

const dymamoDB = new DynamoDB({region: 'us-west-2'});

const data = await dymamoDB.createTable({
    TableName : TABLE_NAME
});
```

Although this approach is not recommended by AWS, implement mocks for it as people may use is in a transition period.

-----

Please vote with 👍 &nbsp; if you need this.

**Comment by ArkadyDR** [comment]
@m-radzikowski given that the V2 SDK compatability functions seem to generally be wrappers around the `send` V3 API functions, aren't already mockable by this library?

(eg see https://github.com/aws/aws-sdk-js-v3/blob/a9259001edb324d19cfca52bd4356a89a73a8806/clients/client-dynamodb/src/DynamoDB.ts#L597 with respect to the example above)

It would mean that authors would need to write their mock setup in the V3 style (ie commands), but it would still "intercept" calls made against the V2 compatability functions.

New to the V3 SDK + this library so I could be missing something :)

**Comment by m-radzikowski** [comment]
This is how I feel right now:

![](https://media.giphy.com/media/yvBAuESRTsETqNFlEl/giphy.gif)

You are 100% correct. I've to only update docs to include the info.
