### ISSUE TITLE
An easy way to test params sent to command

### ISSUE THREAD

**Issue by DominicGBauer** [m-radzikowski/aws-sdk-client-mock#70]
Hi 

First thanks so much for creating this :)!

Second, I was wondering if a function could be made to easily retrieve the params sent to the command

e.g.
```
    EndpointArn: endpointArn ?? '',
    Attributes: {
      Enabled: 'true',
      Token: token,
      CustomUserData: JSON.stringify(userData),
    },
  }
  const updatePlatformEndpoint = snsClient.send(
    new SetEndpointAttributesCommand(params),
  )
```

Then you could have the mock do something like:

```
params = snsMock.on(SetEndpointAttributesCommand).params()
```

So it's easy to test the params being sent through?

**Comment by ehaynes99** [comment]
I was looking for this as well. It would definitely be nice to have something like this built in. I hacked around at it a bit and came up with this:

```typescript
// you will already have this transitive dependency, which is used by all of the v3 sdk client types
import { Command } from '@aws-sdk/smithy-client';
import { AwsStub } from 'aws-sdk-client-mock';

export const getCommandInputs = <T extends Command<any, any, any>>(
  mock: AwsStub<any, any>, //
  commandClass: { new (...args: any[]): T },
) => {
  return mock
    .calls()
    .filter((call) => call.args[0] instanceof commandClass) //
    .map((call) => call.args[0].input as T['input']);
};
```

A simple example of usage:
```typescript
it('gets the url', async () => {
  const mockSqs = mockClient(SQSClient);
  const sqsClient = new SQSClient({});

  await sqsClient.send(new GetQueueUrlCommand({ QueueName: 'test-queue' }));

  // the result is properly typed as `GetQueueUrlCommandInput[]`
  const input = getCommandInputs(mockSqs, GetQueueUrlCommand)[0];
  expect(input).toEqual({ QueueName: 'test-queue' });
});
```

A method on the mock instance itself could probably do a better job of inferring the types and enforce that the supplied command is one that is valid for that particular client type. That could be done with the above, but the types were getting too gnarly for the example to be clear.

**Comment by m-radzikowski** [comment]
I like the idea. I want to spend time on a few other feature requests, but it may be an easy win (thanks for the code @ehaynes99 !) so I will try to include it.

**Comment by wrumsby** [comment]
Noticed this thread and that it hasn't had activity for > 2 years, but you can do something like this using the custom Jest matchers, e.g. if I wanted to test that a DynamoDB update was set with the expected input then I could write the following:

```ts
import 'aws-sdk-client-mock-jest';

...

const expected: UpdateCommandInput = { ... };

expect(ddbMock).toHaveReceivedNthCommandWith(1, UpdateCommand, expected);
```

**Comment by m-radzikowski** [comment]
Yes. In addition, you can use `clientMock.commandCalls()` to get commands of the given type and optionally with a matching input:

```ts
expect(snsMock.commandCalls(PublishCommand)).toHaveLength(1);

expect(snsMock.commandCalls(PublishCommand)[0].args[0].input).toStrictEqual({
    TopicArn: topicArn,
    Message: 'mock message',
});

expect(snsMock.commandCalls(PublishCommand, {Message: 'hello'})).toHaveLength(1);
```

I think this fulfills the needs of params retrieval and validation.
