### ISSUE TITLE
Mocking a specific command only

### ISSUE THREAD

**Issue by svozza** [m-radzikowski/aws-sdk-client-mock#83]
Apologies if I'm missing something obvious here but is there a way for me to only mock a specific command and for the client to use the real behaviour of the client of all the other commands? For a bit of context, I have a bunch of tests that run against `dynamodb-local`. I am trying to test a function that uses the `batchWrite` command but the function I'm testing makes other calls to dynamo before that. I would like to only mock the `batchWrite` function and allow the other commands to pass through to the local DB using the actual SDK. Is this possible?

**Comment by m-radzikowski** [comment]
You can access the underlying [Sinon stub](https://sinonjs.org/releases/v13/stubs/) with:

```ts
mockClient.send
```

There is a `stub.callThrough()` method:

> Causes the original method wrapped into the stub to be called when none of the conditional stubs are matched.

So you can try something like this:

```ts
mockClient.on(BatchWriteItemCommand).resolves({ ... }).
mockClient.send.callThrough();
```

No guarantee it will work, although please let me know if it does (or not).

**Comment by svozza** [comment]
That worked perfectly. Thanks for the prompt reply and moreover, thanks for the great library!

**Comment by m-radzikowski** [comment]
Glad I could help 🙂

**Comment by svozza** [comment]
Btw, if you think this info might be useful to your users, I'm happy to do a PR to add an example to the docs.

**Comment by m-radzikowski** [comment]
Thanks, but there is probably a number of things you could do by utilizing the underlying Sinon stub, and this is just one of them. I don't want the docs to be bloated. But if there will be more questions for this in the future I will add it.

**Comment by svozza** [comment]
Yeah, that makes sense.
