### ISSUE TITLE
Chained behaviors get reset if they are not done in a single chain

### ISSUE THREAD

**Issue by delsinz** [m-radzikowski/aws-sdk-client-mock#85]
If I do:
```javascript
ddbMock.on(QueryCommand).resolvesOnce(validResult);
ddbMock.on(QueryCommand).rejectsOnce(error);
```
instead of
```javascript
ddbMock.on(QueryCommand)
    .resolvesOnce(validResult)
    .rejectsOnce(error);
```
the mock will only reject with `error` once, overwriting the `ddbMock.on(QueryCommand).resolvesOnce(validResult)`.

I'm not sure if this is intended or a bug, but it has caused some great inconvenience for me, making it difficult for me to do something like (unless there are some other clever ways to do it that I couldn't think of):
```javascript
const results = [validResult, error];
results.forEach((res) => {
    if (res instanceOf Error) {
        ddbMock.on(QueryCommand).rejectsOnce(res);
    } else {
        ddbMock.on(QueryCommand).resolvesOnce(res);
    }
})
```
I have to resort to the old workaround for behavior chaining for now:
```javascript
const results = [validResult, error];
results.forEach((res, index) => {
    if (res instanceOf Error) {
        ddbMock.send.onCall(index).rejects(res);
    } else {
        ddbMock.send.onCall(index).resolves(res);
    }
})
```

**Comment by delsinz** [comment]
> That's true - the current implementation requires using the same object instance for `*Once` to work. You can get the command mock instance with `ddbMock.on(QueryCommand)` and then call `resolvesOnce`/`rejectsOnce` multiple time on it and I believe it should work. Something like:
> 
> ```js
> const results = [validResult, error];
> const queryCommandMock = ddbMock.on(QueryCommand);
> results.forEach((res) => {
>     if (res instanceOf Error) {
>         queryCommandMock.rejectsOnce(res);
>     } else {
>         queryCommandMock.resolvesOnce(res);
>     }
> })
> ```
> 
> I'm not sure if the complications in code that would be needed for
> 
> ```js
> ddbMock.on(QueryCommand).resolvesOnce(validResult);
> ddbMock.on(QueryCommand).rejectsOnce(error);
> ```
> 
> to work are worth it, but I agree that the current behavior resetting the mock is not something that you could expect. I will leave this open and maybe try improving it in a spare moment.

I did a quick test on the workaround you provided so I might be wrong here, but it didn't seem to resolve the issue.

**Comment by m-radzikowski** [comment]
@delsinz this snippet works okay:

```ts
it('allows setting multiple Ones', async () => {
    const onPublish = snsMock.on(PublishCommand);
    onPublish.rejectsOnce('one rejection');
    onPublish.resolvesOnce({MessageId: '2'});

    const sns = new SNSClient({});

    await expect(sns.send(new PublishCommand({TopicArn: '', Message: ''}))).rejects.toThrow('one rejection');

    const msg2 = await sns.send(new PublishCommand({TopicArn: '', Message: ''}));
    const msg3 = await sns.send(new PublishCommand({TopicArn: '', Message: ''}));

    expect(msg2.MessageId).toBe('2');
    expect(msg3).toBeUndefined();
});
```
