### ISSUE TITLE
S3Client pass through instead of replaced

### ISSUE THREAD

**Issue by katlim-br** [m-radzikowski/aws-sdk-client-mock#88]
Hello

**I know this is probably a long shot, and a specific use case (though I wonder if others do this as well).**

So we have a singleton `s3Client = new S3Client()` for all our code. And to create helper methods, we are adding it to the instance as in 
```
s3Client.getStream = async function (bucket, object) {}
```

But when I try to do `mockClient(s3Client)`(against the instance, not the class), we end up receiving a `AwsClientStub` instance and our `getStream` method dissapears. Which makes sense.

Would you say is feasible to improve this (I can do the PR if needed) so the instance remains the same, but only the .send method gets stubbed?

I know it could mean a big refactor, though it might bring the benefit that the library is more "compatible" with future AWS updates? not sure really ...

Well thanks

**Comment by m-radzikowski** [comment]
Hey, sorry for the late reply.

I'm not entirely sure why the global singleton would be replaced by the `AwsClientStub`. Only its `send` method should be replaced with a stub, not affecting anything else.

You receive `AwsClientStub` instance from the `mockClient()` method, so you can define stub behaviors. But the global singleton should be unaffected.

Something like this:

```js
import {s3} from './s3.js';

const mockedClient = mockClient(S3Client); // AwsClientStub instance
s3 // your singleton
```

But I may be missing something. If you can create a small repo with the reproduction of your case I can take a look and think how to best support it in the lib.
