### ISSUE TITLE
How to define output for BatchGetCommand

### ISSUE THREAD

**Issue by guyhagemans** [m-radzikowski/aws-sdk-client-mock#89]
hi hi,

I've got the following stub defined:
    ddbMock.on(BatchGetCommand).resolves({
      Item: { id: 'user1', name: 'John' } as unknown,
    });
However I'm getting the following error:
Argument of type '{ Item: unknown; }' is not assignable to parameter of type 'CommandResponse<BatchGetCommandOutput>'.
      Object literal may only specify known properties, and 'Item' does not exist in type 'CommandResponse<BatchGetCommandOutput>'.

Please help with finding a solution for this as I'm lost as how to define this.

thank you so much,
Guy

**Comment by m-radzikowski** [comment]
The [`BatchGetCommand`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/classes/_aws_sdk_lib_dynamodb.batchgetcommand-1.html) accepts and returns objects of types same as [`BatchGetItemCommand`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/batchgetitemcommand.html). The output type is [`BatchGetItemCommandOutput`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/interfaces/batchgetitemcommandoutput.html).

The format is:

```ts
{
  Responses: {
    "tableName": [
      { id: 'user1', name: 'John' }
    ]
  }
}
```

What you provided, the `{Item: {}}` response, would be suitable for [`GetItemCommand`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/classes/_aws_sdk_lib_dynamodb.getcommand-2.html).

You can also take a look at the response docs [here](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html#DDB-BatchGetItem-response-Responses).

**Comment by guyhagemans** [comment]
super, thank you so much!
