### ISSUE TITLE
Cognito - SignUpCommand issue

### ISSUE THREAD

**Issue by chops318** [m-radzikowski/aws-sdk-client-mock#91]
**Checklist**

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**
I am using NestJS and trying to mock out the CognitoIdentityProvider.  I do this in a beforeEach via
```
    const cognito = new CognitoIdentityProvider({ region: 'local' });
    cgMock = mockClient(cognito);
    cgMock.reset();
```

```
  it('creates a new user', async () => {
    const mockUser = {
      UserSub: 'asdfasfd',
      $metadata: {
        attempts: 0,
      },
      UserConfirmed: true,
      AuthenticationResult: {
        RefreshToken: 'asdfafsd',
        AccessToken: 'asdfasdf',
        IdToken: 'asdfasdf',
      },
    };

    cgMock.onAnyCommand().resolvesOnce(mockUser);
    const user = await service.register({
      username: '<email>',
      password: '<password>',
    });
    expect(user).toBeDefined();
    expect(user.email).toBe('<email>');
  });
```
If I set a bogus ClientId, I get a ResourceNotFoundException, but if I provide a valid ClientId, the command gets sent onto Cognito and the user is created. I'm unsure if I am doing anything incorrect, but it seems as if the mock is not intercepting the command sent to Cognito

**Environment**

- Node version: `v16.13.2`
- Testing lib and version: `Jest - 27.2.5`
- Typescript version: `4.3.5`
- AWS SDK v3 Client mock version: `0.6.2`
- AWS JS SDK libs and versions:
  - `@aws-sdk/client-cognito-identity - 3.76.0`
  - `@aws-sdk/client-cognito-identity-provider - 3.76.0`

**Comment by TylerSustare** [comment]
@chops318 Why did you close this? Did you find a solution? I'm running into the same issue with DynamoDB and query commands #141
