### ISSUE TITLE
libStorage.d.ts - Cannot find module '@aws-sdk/client-s3' or its corresponding type declarations

### ISSUE THREAD

**Issue by JasperHub1** [m-radzikowski/aws-sdk-client-mock#92]
**Checklist**

- [x] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**
`node_modules/aws-sdk-client-mock/dist/types/libStorage.d.ts(8,95): error TS2307: Cannot find module '@aws-sdk/client-s3' or its corresponding type declarations.`

**Environment**

- Node version: v16.14.2
- Testing lib and version: Jest v27.4.6
- Typescript version: v4.4.4
- AWS SDK v3 Client mock version: 0.6.2
- AWS JS SDK libs and versions: NA

**Comment by m-radzikowski** [comment]
@JasperHub1 please provide a repo with reproduction, including the command you use to run the test.

**Comment by JasperHub1** [comment]
@m-radzikowski, sorry could't share due to its private repo

the work around is to use [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) option

Also another option was to install `@aws-sdk/client-s3` to project as it's having peer dependencies

Saw you opened this PR https://github.com/m-radzikowski/aws-sdk-client-mock/pull/57 before, might related to this issue

**Comment by studiojms** [comment]
I have the same issue using the lib with typescript. Does anyone have any definitive solution?

**Comment by m-radzikowski** [comment]
I've just released a v1.0.0 that removes the `@aws-sdk/client-s3` from peer dependencies. I believe it should solve the problem.

Otherwise, please reopen / open a new issue, providing a simple, small repository with your configuration that will reproduce the issue.

**Comment by studiojms** [comment]
Using the new version (v1.0.0) I'm getting an error related to `NativeAttributeBinary` type:

```sh
node_modules/@aws-sdk/util-dynamodb/dist-types/models.d.ts:19:86 - error TS2304: Cannot find name 'File'.

19 export declare type NativeAttributeBinary = ArrayBuffer | Blob | Buffer | DataView | File | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | BigInt64Array | BigUint64Array;
                                                                                        ~~~~


Found 1 error in node_modules/@aws-sdk/util-dynamodb/dist-types/models.d.ts:19

```

**Comment by JasperHub1** [comment]
We upgraded to v1.0.0 and no longer having the peer dependency issue. 👏  Thanks

**Comment by m-radzikowski** [comment]
> Using the new version (v1.0.0) I'm getting an error related to `NativeAttributeBinary` type:

@studiojms this doesn't seem like a mocking library issue. See https://github.com/aws/aws-sdk-js-v3/issues/2896
But if you are confident it happens only when the mocking library in v1.0.0 is added to the project, please open a new issue, preferably with a repo reproducing the issue.
