### ISSUE TITLE
Jest matchers don't allow use of jest submatchers for input object filtering

### ISSUE THREAD

**Issue by taschmidt** [m-radzikowski/aws-sdk-client-mock#98]
**Checklist**

- [x] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**

The Jest matchers added [here](https://github.com/m-radzikowski/aws-sdk-client-mock/pull/97) still use the sinon call matching logic [here](https://github.com/jurijzahn8019/aws-sdk-client-mock/blob/7f3fb04d8e352f254c7b6e8ab58fbb9ecb0e3f7c/src/jestMatchers.ts#L222) so jest submatchers don't work. For example, I would expect this code to work:

```
expect(mock).toHaveReceivedCommandWith(QueryCommand, {
    TableName: expect.stringMatching(/^foo/)
});
```

Instead I get the following error:
```
Error: Expected DynamoDBDocumentClient to receive "QueryCommand" with {"TableName": StringMatching /^foo-/}
DynamoDBDocumentClient received "QueryCommand" 0 times
Calls:

  1. QueryCommand: {"ExpressionAttributeValues": {":guid": "guid"}, "KeyConditionExpression": "id = :guid", "Limit": 1, "ScanIndexForward": false, "TableName": "foo-undefined"}
```

**Environment**

- Node version: 14.19.3
- Testing lib and version: Jest
- Typescript version: 4.2.4
- AWS SDK v3 Client mock version: 1.0.0
- AWS JS SDK libs and versions:
  - @aws-sdk/client-dynamodb: 3.49.0
  - @aws-sdk/lib-dynamodb: 3.49.0

**Comment by taschmidt** [comment]
I played around and it seems to work if I add this function:
```
function checkMatch(callInput, input) {
    try {
        expect(callInput).toMatchObject(input);
        return true;
    } catch {
        return false;
    }
}
```

and then change [this line](https://github.com/m-radzikowski/aws-sdk-client-mock/blob/7a26a2145b6a4fc81bb0bb92bdcf954e64990b5a/src/jestMatchers.ts#L208) to this:
```
const commandCalls = calls.filter(call =>
    call.args[0] instanceof command && checkMatch(call.args[0].input, input)
);
```

But I don't know if that's the recommended approach.

**Comment by m-radzikowski** [comment]
Thank you, I will check what's the standard way of achieving this with custom Jest matchers and make an update.

**Comment by bernardobridge** [comment]
Running into this issue too, when migrating from v2 to v3 and trying to update our tests :(.

**Comment by m-radzikowski** [comment]
I did some work in this regard on the `jest-matchers-asymmetric` branch. I think I have this figured out. I did not proceed with merging it because I think I will need to extract Jest matchers as a separate package anyway due to conflicts when using Mocha (#101).

I can't provide you with a date when I will sit and work on this but will try to make it sooner than later.

**Comment by taschmidt** [comment]
Great news @m-radzikowski !

**Comment by m-radzikowski** [comment]
Merged, I will update later on the release.

**Comment by m-radzikowski** [comment]
Jest matchers were moved to a separate package: `aws-sdk-client-mock-jest`.

It was just released as a beta version (`v2.0.0-beta.2`). The corresponding beta release of the main package, `aws-sdk-client-mock`, does not include Jest matchers anymore.

**Comment by taschmidt** [comment]
Thanks @m-radzikowski !! What was the reasoning behind the separate packages?

**Comment by m-radzikowski** [comment]
#101
